### ISSUE TITLE
Cannot have plugin lookup work - issue with bs4 formatting?

### ISSUE THREAD

**Issue by TheSleepySlee** [hangoutsbot/hangoutsbot#195]
Hi,

I have installed everything, and bot is running correctly, responds to various commands.
However, when I try to enable the lookup plugin, using the example spreadsheet, I am facing issues.
I have modified the JSON file correctly, and enabled spreadsheets with true as well as lookup plugin, and linked to default example spreadsheet. I see lookup being loaded when the bot starts.

All plugins seems to be installed, however I admit not being able to install pip3, so seems only pip2.7 was run when reading the "requirements.txt" file.

Here is the console output related to the issue:
```
message: plugins.mentions._handle_mention : coroutine
message: plugins.restrictedadd._verify_botkeeper_presence : coroutine
message: plugins.simplytranslate._handle_message : coroutine
message: plugins.subscribe._handle_keyword : coroutine
Keyword: azerty Max Counter: 5
XXX sleepy (10*******************) has requested to lookup 'azerty'
EXCEPTION in CommandDispatcher.run: lookup
```

Here is the error log I am seeing: do you really think this is due to not using pip3 ? Thanks
```
2015-06-28 22:47:22,936 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): accounts.google.com
2015-06-28 22:47:23,028 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): accounts.google.com
2015-06-28 22:47:23,253 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): www.google.com
2015-06-28 22:47:23,363 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): www.google.fr
2015-06-28 22:47:23,754 - root - INFO - _load_hooks(): 0 hook(s) loaded
2015-06-28 22:47:23,755 - root - INFO - _start_sinks(): 0 sink thread(s) started
2015-06-28 22:47:46,551 - root - ERROR - CommandDispatcher.run: lookup
Traceback (most recent call last):
  File "/home/sleepy/hangupsbot/hangupsbot/commands.py", line 42, in run
    yield from func(bot, event, *args, **kwds)
  File "/usr/lib/python3.4/asyncio/coroutines.py", line 141, in coro
    res = func(*args, **kw)
  File "/home/sleepy/hangupsbot/hangupsbot/plugins/lookup.py", line 49, in lookup
    from bs4 import BeautifulSoup
  File "/home/sleepy/.local/lib/python3.4/site-packages/bs4/__init__.py", line 175
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

**Comment by endofline** [comment]
Based on the explanation, your problem might be your pip version. 

There are several ways to get pip3 installed, but I tend to use this one in crush (YMMV):
```
wget https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py
```
To get the latest version of pip3 installed, then try reinstalling all your dependencies again.

**Comment by TheSleepySlee** [comment]
Thanks, as expected, this was the issue. Above commands did not really help, as I was not root on this machine. I decided to use Virtualenv, as described in link below, and now works like a charm:
http://askubuntu.com/questions/412178/how-to-install-pip-for-python-3-in-ubuntu-12-04-lts
