### ISSUE TITLE
Bot does not run out of the box

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#269]
I just deployed a new bot today off of staging, but it doesn't seem to want to run:
```
HangupsBot: memory file will be used: /root/.local/share/dany/memory.json
Connected!
Client unexpectedly disconnected:
local variable 'changed' referenced before assignment
Waiting 5 seconds...
Trying to connect again (try 1 of 5)...
Connected!
Client unexpectedly disconnected:
reprocessor.attach_reprocessor already registered in shared
Waiting 10 seconds...
Trying to connect again (try 2 of 5)...
```

The first error:
```
2015-07-22 18:04:24,466 - root - ERROR - CLIENT: unrecoverable low-level error
Traceback (most recent call last):
  File "/root/hangupsbot/hangupsbot/hangupsbot.py", line 233, in run
    loop.run_until_complete(self._client.connect())
  File "/usr/local/lib/python3.4/dist-packages/asyncio-3.4.3-py3.4.egg/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.4/dist-packages/asyncio-3.4.3-py3.4.egg/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/local/lib/python3.4/dist-packages/asyncio-3.4.3-py3.4.egg/asyncio/tasks.py", line 234, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.4/dist-packages/hangups-0.2.9-py3.4.egg/hangups/client.py", line 122, in connect
    yield from self._listen_future
  File "/usr/local/lib/python3.4/dist-packages/asyncio-3.4.3-py3.4.egg/asyncio/futures.py", line 386, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.4/dist-packages/asyncio-3.4.3-py3.4.egg/asyncio/tasks.py", line 287, in _wakeup
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/asyncio-3.4.3-py3.4.egg/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/local/lib/python3.4/dist-packages/asyncio-3.4.3-py3.4.egg/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/usr/local/lib/python3.4/dist-packages/hangups-0.2.9-py3.4.egg/hangups/channel.py", line 204, in listen
    yield from self._longpoll_request()
  File "/usr/local/lib/python3.4/dist-packages/hangups-0.2.9-py3.4.egg/hangups/channel.py", line 355, in _longpoll_request
    yield from self._on_push_data(chunk)
  File "/usr/local/lib/python3.4/dist-packages/hangups-0.2.9-py3.4.egg/hangups/channel.py", line 382, in _on_push_data
    yield from self.on_connect.fire()
  File "/usr/local/lib/python3.4/dist-packages/hangups-0.2.9-py3.4.egg/hangups/event.py", line 50, in fire
    yield from gen
  File "/usr/local/lib/python3.4/dist-packages/hangups-0.2.9-py3.4.egg/hangups/client.py", line 114, in _on_connect
    yield from self.on_connect.fire(initial_data)
  File "/usr/local/lib/python3.4/dist-packages/hangups-0.2.9-py3.4.egg/hangups/event.py", line 50, in fire
    yield from gen
  File "/root/hangupsbot/hangupsbot/hangupsbot.py", line 597, in _on_connect
    self.conversations = conversation_memory(self)
  File "/root/hangupsbot/hangupsbot/utils.py", line 74, in __init__
    self.standardise_memory()
  File "/root/hangupsbot/hangupsbot/utils.py", line 163, in standardise_memory
    return changed
UnboundLocalError: local variable 'changed' referenced before assignment
```

On the retry, this error comes up:
```
2015-07-22 18:07:26,575 - root - ERROR - CLIENT: unrecoverable low-level error
Traceback (most recent call last):
  File "/root/hangupsbot/hangupsbot/hangupsbot.py", line 233, in run
    loop.run_until_complete(self._client.connect())
  File "/usr/local/lib/python3.4/dist-packages/asyncio-3.4.3-py3.4.egg/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.4/dist-packages/asyncio-3.4.3-py3.4.egg/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/local/lib/python3.4/dist-packages/asyncio-3.4.3-py3.4.egg/asyncio/tasks.py", line 234, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.4/dist-packages/hangups-0.2.9-py3.4.egg/hangups/client.py", line 122, in connect
    yield from self._listen_future
  File "/usr/local/lib/python3.4/dist-packages/asyncio-3.4.3-py3.4.egg/asyncio/futures.py", line 386, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.4/dist-packages/asyncio-3.4.3-py3.4.egg/asyncio/tasks.py", line 287, in _wakeup
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/asyncio-3.4.3-py3.4.egg/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/local/lib/python3.4/dist-packages/asyncio-3.4.3-py3.4.egg/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/usr/local/lib/python3.4/dist-packages/hangups-0.2.9-py3.4.egg/hangups/channel.py", line 204, in listen
    yield from self._longpoll_request()
  File "/usr/local/lib/python3.4/dist-packages/hangups-0.2.9-py3.4.egg/hangups/channel.py", line 355, in _longpoll_request
    yield from self._on_push_data(chunk)
  File "/usr/local/lib/python3.4/dist-packages/hangups-0.2.9-py3.4.egg/hangups/channel.py", line 382, in _on_push_data
    yield from self.on_connect.fire()
  File "/usr/local/lib/python3.4/dist-packages/hangups-0.2.9-py3.4.egg/hangups/event.py", line 50, in fire
    yield from gen
  File "/usr/local/lib/python3.4/dist-packages/hangups-0.2.9-py3.4.egg/hangups/client.py", line 114, in _on_connect
    yield from self.on_connect.fire(initial_data)
  File "/usr/local/lib/python3.4/dist-packages/hangups-0.2.9-py3.4.egg/hangups/event.py", line 50, in fire
    yield from gen
  File "/root/hangupsbot/hangupsbot/hangupsbot.py", line 573, in _on_connect
    self._handlers = handlers.EventHandler(self)
  File "/root/hangupsbot/hangupsbot/handlers.py", line 32, in __init__
    bot.register_shared('reprocessor.attach_reprocessor', self.attach_reprocessor)
  File "/root/hangupsbot/hangupsbot/hangupsbot.py", line 191, in register_shared
    raise RuntimeError(message)
RuntimeError: reprocessor.attach_reprocessor already registered in shared
```

**Comment by endofline** [comment]
Will fix this in next 3 hours. Missed a parameter in utils.py
