### ISSUE TITLE
in default plugin: broadcast remove broken (doesn't use permamem)

### ISSUE THREAD

**Issue by FrNico** [hangoutsbot/hangoutsbot#313]
Seems "remove <text>" is broken in broadcast remove command:

```
2015-08-13 01:55:25 ERROR commands: CommandDispatcher.run: broadcast
Traceback (most recent call last):
  File "/opt/hangoutsbot/hangupsbot/commands.py", line 56, in run
    yield from func(bot, event, *args, **kwds)
  File "/usr/lib/python3.4/asyncio/coroutines.py", line 141, in coro
    res = func(*args, **kw)
  File "/opt/hangoutsbot/hangupsbot/plugins/default.py", line 255, in broadcast
    removed.append("<b>{}</b> ({})".format(bot.conversations.get_name(conv), convid))
NameError: name 'conv' is not defined
```

**Comment by endofline** [comment]
Added to #300
