### ISSUE TITLE
cleverbot plugin broken - when issuing "chat" command

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#317]
Crappy bug report, just submitting for later memory triggers, I may debug this further later.

```
Aug 14 14:16:56 ingress hangupsbot.py[10034]: 14:16:56 ERROR commands: RUN: chat
Aug 14 14:16:56 ingress hangupsbot.py[10034]: Traceback (most recent call last):
Aug 14 14:16:56 ingress hangupsbot.py[10034]: File "/home/discobot/hangoutsbot/hangupsbot/commands/__init__.py", line 177, in run
Aug 14 14:16:56 ingress hangupsbot.py[10034]: yield from func(bot, event, *args, **kwds)
Aug 14 14:16:56 ingress hangupsbot.py[10034]: File "/home/discobot/hangoutsbot/hangupsbot/plugins/cleverbot.py", line 198, in chat
Aug 14 14:16:56 ingress hangupsbot.py[10034]: text = yield from loop.run_in_executor(None, __cleverbots[event.conv.id_].ask, ' '.join(args))
Aug 14 14:16:56 ingress hangupsbot.py[10034]: File "/usr/local/lib/python3.4/asyncio/futures.py", line 386, in __iter__
Aug 14 14:16:56 ingress hangupsbot.py[10034]: yield self  # This tells Task to wait for completion.
Aug 14 14:16:56 ingress hangupsbot.py[10034]: File "/usr/local/lib/python3.4/asyncio/tasks.py", line 287, in _wakeup
Aug 14 14:16:56 ingress hangupsbot.py[10034]: value = future.result()
Aug 14 14:16:56 ingress hangupsbot.py[10034]: File "/usr/local/lib/python3.4/asyncio/futures.py", line 275, in result
Aug 14 14:16:56 ingress hangupsbot.py[10034]: raise self._exception
Aug 14 14:16:56 ingress hangupsbot.py[10034]: File "/usr/local/lib/python3.4/concurrent/futures/thread.py", line 54, in run
Aug 14 14:16:56 ingress hangupsbot.py[10034]: result = self.fn(*self.args, **self.kwargs)
Aug 14 14:16:56 ingress hangupsbot.py[10034]: File "/home/discobot/hangoutsbot/hangupsbot/plugins/cleverbot.py", line 111, in ask
Aug 14 14:16:56 ingress hangupsbot.py[10034]: parsed = self._parse()
Aug 14 14:16:56 ingress hangupsbot.py[10034]: File "/home/discobot/hangoutsbot/hangupsbot/plugins/cleverbot.py", line 165, in _parse
Aug 14 14:16:56 ingress hangupsbot.py[10034]: 'conversation_log_id': parsed[0][2],
Aug 14 14:16:56 ingress hangupsbot.py[10034]: IndexError: list index out of range
```

**Comment by endofline** [comment]
talking to the cleverbot "api" is a horrible beast ;P the original devs keep changing their protocol to confound "leechers" ;P

**Comment by endofline** [comment]
The original code for this plugin, specifically the part that actually talks to the web front-end of cleverbot is derived from https://github.com/folz/cleverbot.py, adapted from its Py2 roots to Py3

**Comment by endofline** [comment]
Can't repeat this error - perhaps its a transient cleverbot server bug? - Mine seems to be working fine. I'll leave this issue open but remove it as a blocker.

**Comment by pleasantone** [comment]
Looks like a transient bug, it's working fine now.

**Comment by endofline** [comment]
Broke again: getting `list index out of range`

**Comment by endofline** [comment]
And after being down for around 12 hours, it seems to have gone up again - I'm adding in additional checks for this kind of error and leaving this issue open until a more permanent solution can be found.

**Comment by endofline** [comment]
New command `/bot chatreset` allows conversation api instances to be restarted. Wiki updated: https://github.com/hangoutsbot/hangoutsbot/wiki/Cleverbot-Plugin#admin-commands
