### ISSUE TITLE
Slack module exception with failed photo_url

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#336]
```
ERROR plugins.slack: FAILED to acquire photo_url for XXXX XXXX
Traceback (most recent call last):
  File "/home/discobot/hangoutsbot/hangupsbot/plugins/slack.py", line 184, in _handle_slackout
    photo_url = "http:" + response.entities[0].properties.photo_url
TypeError: Can't convert 'NoneType' object to str implicitly
ERROR plugins.slack: Could not handle slackout with key xoxb-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX between #XXXXXXXXXXXXXXX and ['XXXXXXXXXXXXXXXXXXXXXXXXXX']. Is config.json properly configured?
Traceback (most recent call last):
  File "/home/discobot/hangoutsbot/hangupsbot/plugins/slack.py", line 189, in _handle_slackout
    client.chat_post_message(channel, event.text, username=fullname, icon_url=photo_url)
UnboundLocalError: local variable 'photo_url' referenced before assignment
```

**Comment by pleasantone** [comment]
https://gist.github.com/pleasantone/0b44133f22d94a725537

**Comment by endofline** [comment]
The `photo_url` issue should be fixed - the gist contents also contains an ssl verification upgrade that is more applicable to #237

**Comment by endofline** [comment]
Verified in #331
