### ISSUE TITLE
Bot Addme broken?

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#343]
Staging as of today... preliminary issue report as a memory-holder (I'm working on Slack right now).

![screen shot 2015-08-19 at 3 18 16 pm](https://cloud.githubusercontent.com/assets/5339793/9370494/923be7e2-4685-11e5-887e-fec9292dca85.png)

```
Aug 19 15:13:56 ingress hangupsbot[31482]: ERROR commands: RUN: user
Aug 19 15:13:56 ingress hangupsbot[31482]: Traceback (most recent call last):
Aug 19 15:13:56 ingress hangupsbot[31482]: File "/home/discobot/hangoutsbot/hangupsbot/commands/__init__.py", line 177, in run
Aug 19 15:13:56 ingress hangupsbot[31482]: results = yield from func(bot, event, *args, **kwds)
Aug 19 15:13:56 ingress hangupsbot[31482]: TypeError: user() missing 1 required positional argument: 'username'
Aug 19 15:15:06 ingress hangupsbot[31482]: INFO root: get_1on1: remembered UgwVk3ytehRTIoEH_3N4AaABAQ for 108909027823068494460
Aug 19 15:15:26 ingress hangupsbot[31482]: INFO plugins.convtools: addusers: ['108909027823068494460'] into conversation text:FiDi
Aug 19 15:15:26 ingress hangupsbot[31482]: WARNING monkeypatch.otr_support: missing history flag: text:FiDi
Aug 19 15:15:27 ingress hangupsbot[31482]: ERROR commands: RUN: addme
Aug 19 15:15:27 ingress hangupsbot[31482]: Traceback (most recent call last):
Aug 19 15:15:27 ingress hangupsbot[31482]: File "/home/discobot/hangoutsbot/hangupsbot/commands/__init__.py", line 177, in run
Aug 19 15:15:27 ingress hangupsbot[31482]: results = yield from func(bot, event, *args, **kwds)
Aug 19 15:15:27 ingress hangupsbot[31482]: File "/home/discobot/hangoutsbot/hangupsbot/plugins/convtools.py", line 50, in addme
Aug 19 15:15:27 ingress hangupsbot[31482]: yield from addusers(bot, event, *[event.user.id_.chat_id, "into", target_conv])
Aug 19 15:15:27 ingress hangupsbot[31482]: File "/home/discobot/hangoutsbot/hangupsbot/plugins/convtools.py", line 42, in addusers
Aug 19 15:15:27 ingress hangupsbot[31482]: yield from bot._client.adduser(target_conv, list_add)
Aug 19 15:15:27 ingress hangupsbot[31482]: File "/home/discobot/hangoutsbot/hangupsbot/monkeypatch/otr_support.py", line 103, in otr_monkeypatched_adduser
Aug 19 15:15:27 ingress hangupsbot[31482]: .format(res_status))
Aug 19 15:15:27 ingress hangupsbot[31482]: hangups.exceptions.NetworkError: Unexpected status: ERROR_INVALID_CONVERSATION
Aug 19 15:15:50 ingress hangupsbot[31482]: INFO plugins.convtools: addusers: ['108909027823068494460'] into conversation UgyS8TvClcBbYeFUBmF4AaABAQ
Aug 19 15:15:50 ingress hangupsbot[31482]: ERROR commands: RUN: addme
Aug 19 15:15:50 ingress hangupsbot[31482]: Traceback (most recent call last):
Aug 19 15:15:50 ingress hangupsbot[31482]: File "/home/discobot/hangoutsbot/hangupsbot/commands/__init__.py", line 177, in run
Aug 19 15:15:50 ingress hangupsbot[31482]: results = yield from func(bot, event, *args, **kwds)
Aug 19 15:15:50 ingress hangupsbot[31482]: File "/home/discobot/hangoutsbot/hangupsbot/plugins/convtools.py", line 50, in addme
Aug 19 15:15:50 ingress hangupsbot[31482]: yield from addusers(bot, event, *[event.user.id_.chat_id, "into", target_conv])
Aug 19 15:15:50 ingress hangupsbot[31482]: File "/home/discobot/hangoutsbot/hangupsbot/plugins/convtools.py", line 42, in addusers
Aug 19 15:15:50 ingress hangupsbot[31482]: yield from bot._client.adduser(target_conv, list_add)
Aug 19 15:15:50 ingress hangupsbot[31482]: File "/home/discobot/hangoutsbot/hangupsbot/monkeypatch/otr_support.py", line 103, in otr_monkeypatched_adduser
Aug 19 15:15:50 ingress hangupsbot[31482]: .format(res_status))
Aug 19 15:15:50 ingress hangupsbot[31482]: hangups.exceptions.NetworkError: Unexpected status: ERROR_INVALID_REQUEST
```

**Comment by endofline** [comment]
Tried to repeat this:
* `/bot addme` - no response (will fix this)
* `/bot addme XYZ` - `NetworkError: Unexpected status: ERROR_INVALID_CONVERSATION` (expected)
* `/bot addme <valid conv id>` - adds me to the valid conversation, no error and no other output

Is your error when adding to a valid conversation repeatable?

**Comment by pleasantone** [comment]
Was unable to reproduce the failure when I attempted to add myself to a valid group.

**Comment by endofline** [comment]
Some changes were made in latest staging and might be related to this issue (re: #368, 1d3ccc8)

**Comment by pleasantone** [comment]
Confirmed.
