### ISSUE TITLE
Unhandled traceback - network error in @mentions - (gatewayed from slack -> HO)

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#347]
In this conversation, a Slack user was doing an @mention of an -unknown/unregistered- user on hangouts. I have not debugged further, yet.  Just a memory placeholder.

Started further debugging, it doesn't seem to happen when the @-mention comes in via hangouts, only seeing it on the gateway'ed message from slack, which makes absolutely no sense to me. I think there is a failure in my debugging

```
INFO sinks.base_bot_request_handler: SlackAsyncListener: sending segments: 3
INFO aiohttp.access: 127.0.0.1 - - Fri, 21 Aug 2015 17:36:43 GMT "POST /UXXXXXXXXXXXXXXXABAQ HTTP/1.1" 200 162 "-" "Slackbot 1.0 (+https://api.slack.com/robots)"
INFO event: eid/dt: 7-H0Z7-MC7K837MnKPl7XF/2015-08-21 10:36:42
INFO event: cid/cn: U<valid-chan-id>ABAQ|<valid-channel-name>
INFO event: c/g/un: 100<user-id-of-discobot>/Disco Bot
INFO event: len/tx: 51/<slack-user>: @<hangouts-user> were you in the car at the time?
INFO handlers: reprocessor uuid found: 0a980f32-181c-4b98-927d-XXXXXXXXXXXXXne=False
INFO root: get_1on1: creating 1to1 with 100<valid-userid-of-hangouts-user>
ERROR root: GET_1TO1: failed to create 1-to-1 for user 100<valid-userid-of-hangouts-user>
Traceback (most recent call last):
  File "./hangupsbot.py", line 451, in get_1to1
    response = yield from self._client.createconversation([chat_id])
  File "/usr/local/lib/python3.4/site-packages/hangups/client.py", line 854, in createconversation
    .format(res_status))
hangups.exceptions.NetworkError: Unexpected status: ERROR_INVALID_REQUEST
INFO plugins.mentions: @mention '<hangouts-user>' in '<hangout-name>' (U<hangout-id>ABAQ)
```

**Comment by pleasantone** [comment]
Just saw it again, had nothing to do with slack:

```
2015-08-21 12:17:02 INFO root: get_1on1: remembered UgwVk3ytehRTIoEH_3N4AaABAQ for 108909027823068494460
2015-08-21 12:17:02 ERROR root: CORO_SEND_MESSAGE: error sending UgwVk3ytehRTIoEH_3N4AaABAQ
Traceback (most recent call last):
  File "/home/discobot/hangoutsbot/hangupsbot/hangupsbot.py", line 749, in coro_send_message
    otr_status=otr_status )
  File "/home/pst/hangoutsbot/hangupsbot/hangups_conversation.py", line 162, in send_message
    image_id=image_id, otr_status=otr_status
  File "/usr/local/lib/python3.4/site-packages/hangups/client.py", line 436, in sendchatmessage
    .format(res_status))
hangups.exceptions.NetworkError: Unexpected status: ERROR_UNEXPECTED
```

**Comment by endofline** [comment]
All of these errors are being raised from the hangups client - per chance do you run an extremely busy bot? We are aware that some kinds of activity gets throttled after awhile - like creating too many conversations in too short a time frame. Unfortunately, we don't have exact numbers on this, and no predictable way to determine when a failure might occur.

**Comment by pleasantone** [comment]
It got busier yesterday when I started gatewaying slack and hangouts, but no, no more than 2 messages a second peak, and very few creates, even 1on1s. I'll keep the log in debug mode and watch like a hawk

**Comment by pleasantone** [comment]
I haven't seen this in a while, closing.
