### ISSUE TITLE
/bot ask with no parameters - exception generated

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#350]
User issued "/bot ask" --

```
ERROR commands: RUN: ask
Traceback (most recent call last):
  File "/home/pst/hangoutsbot/hangupsbot/commands/__init__.py", line 177, in run
    results = yield from func(bot, event, *args, **kwds)
  File "/home/pst/hangoutsbot/hangupsbot/plugins/wolframalpha.py", line 33, in ask
    res = _internal["client"].query(keyword)
  File "/usr/local/lib/python3.4/site-packages/wolframalpha/__init__.py", line 79, in query
    return Result(resp)
  File "/usr/local/lib/python3.4/site-packages/wolframalpha/__init__.py", line 11, in __init__
    self._handle_error()
  File "/usr/local/lib/python3.4/site-packages/wolframalpha/__init__.py", line 21, in _handle_error
    raise Exception(tmpl.format(code=code, msg=msg))
Exception: Error 1000: input parameter not present in query
```

Pull request #351 fixes this.

**Comment by endofline** [comment]
Added to #354
