### ISSUE TITLE
botalive plugin fails to load

### ISSUE THREAD

**Issue by nvrrvn** [hangoutsbot/hangoutsbot#359]
ERROR plugins: EXCEPTION during plugin init: plugins.botalive
Traceback (most recent call last):
  File "<somepath>/hangupsbot/plugins/__init__.py", line 359, in load
    the_function(bot)
  File "<somepath>/hangupsbot/plugins/botalive.py", line 35, in _initialise
    plugins.start_asyncio_task(_periodic_watermark_update, config_botalive)
  File "<somepath>/hangupsbot/plugins/__init__.py", line 180, in start_asyncio_task
    task = loop.create_task(coroutine_function(tracking.bot, *args, **kwargs))
AttributeError: '_UnixSelectorEventLoop' object has no attribute 'create_task'

**Comment by endofline** [comment]
Sounds like you're running an older version of Python - you need at least [python 3.4.2](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.BaseEventLoop.create_task)

**Comment by nvrrvn** [comment]
Thanks for the pointer. The hoster had symlinked an older version.
