### ISSUE TITLE
pushpullet mention broken for pushbullet.py 0.8.0

### ISSUE THREAD

**Issue by j16sdiz** [hangoutsbot/hangoutsbot#360]
Pushbullet support is broken because of this commit: randomchars/pushbullet.py@b420f4614f

```
2015-08-24 08:24:29 ERROR commands: RUN: mention
Traceback (most recent call last):
  File "/home/hangups/hk_staging/hangupsbot/commands/__init__.py", line 177, in run
    results = yield from func(bot, event, *args, **kwds)
  File "/home/hangups/hk_staging/hangupsbot/plugins/mentions.py", line 303, in mention
    event.text)
ValueError: too many values to unpack (expected 2)
```

**Comment by endofline** [comment]
This will probably still need backward-compatibility hacks to keep it running for people who never bothered to upgrade their pushbullet library

**Comment by j16sdiz** [comment]
Thanks
