### ISSUE TITLE
/bot addme returns error after successfully executing

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#375]
After using /bot addme, it works, and then a few seconds later throws an error:

```
03:20:21 INFO event: len/tx: 40//bot addme UgxXXXXXXXXXXXXXXXAaABAQ
03:20:21 INFO plugins.convtools: addusers: ['109883513693796164843'] into conversation UgxXXXXXXXXXXXXXXXAaABAQ
03:20:27 INFO event: eid/dt: 7-H0Z7-C7JN83SnDH87hbU/2015-08-30 03:20:22
03:20:27 INFO event: cid/cn: UgxXXXXXXXXXXXXXXXAaABAQ/🐢 Test Chat
03:20:27 INFO event: c/g/un: 106XXXXXXXXXXXXXXXX/106XXXXXXXXXXXXXXXX/Hangouts Bot
03:20:27 INFO event: len/tx: 0/
03:20:27 INFO permamem: conv participants changed 🐢 Test Chat (UgxXXXXXXXXXXXXXXXAaABAQ)
03:20:27 INFO permamem: conv UgxXXXXXXXXXXXXXXXAaABAQ updated 🐢 Test Chat
03:20:28 INFO config: /root/.local/share/hangupsbot/memory.json write 0.1440906524658203
03:20:36 ERROR commands: RUN: addme
Traceback (most recent call last):
  File "/root/hangoutsbot/hangoutsbot/hangupsbot/commands/__init__.py", line 178, in run
    results = yield from func(bot, event, *args, **kwds)
  File "/root/hangoutsbot/hangoutsbot/hangupsbot/plugins/convtools.py", line 50, in addme
    yield from addusers(bot, event, *[event.user.id_.chat_id, "into", target_conv])
  File "/root/hangoutsbot/hangoutsbot/hangupsbot/plugins/convtools.py", line 42, in addusers
    yield from bot._client.adduser(target_conv, list_add)
  File "/root/hangoutsbot/hangoutsbot/hangupsbot/monkeypatch/otr_support.py", line 103, in otr_monkeypatched_adduser
    .format(res_status))
hangups.exceptions.NetworkError: Unexpected status: ERROR_UNEXPECTED

```

**Comment by endofline** [comment]
Maybe related to #343 - pull latest staging and repeat the test in debug mode - recent commits added a [user check + batch adding](https://github.com/hangoutsbot/hangoutsbot/commit/1d3ccc8659d76680d87945c020c8fe6e25e7bdbf)

**Comment by nylonee** [comment]
Latest staging works. Thanks. Closing this
