### ISSUE TITLE
ValueError: Message expected list but got str

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#376]
Getting this error when I attempt to start the bot, on second attempt the error disappears and the bot starts successfully.
```
03:22:10 ERROR root: CLIENT: unrecoverable low-level error
Traceback (most recent call last):
  File "/root/hangoutsbot/hangoutsbot/hangupsbot/hangupsbot.py", line 164, in run
    loop.run_until_complete(self._client.connect())
  File "/usr/local/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/local/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/usr/local/lib/python3.4/site-packages/hangups/client.py", line 109, in connect
    initial_data = yield from self._initialize_chat()
  File "/usr/local/lib/python3.4/site-packages/hangups/client.py", line 247, in _initialize_chat
    data_dict['ds:20'][0]
  File "/usr/local/lib/python3.4/site-packages/hangups/pblite.py", line 149, in parse
    .format(type(input_)))
ValueError: Message expected list but got <class 'str'>
```

**Comment by endofline** [comment]
Presuming this is an FYI, I get this on very rare occasions - it appears that the Hangouts server returns  a different payload when this happens but I haven't got the opportunity to retrieve the actual payload  - if and when we do, it should be escalated to the hangups project

**Comment by tdryer** [comment]
The flaky parsing code in hangups that causes this was removed in https://github.com/tdryer/hangups/commit/b4567ad832b9fb42c7930b09ee5f6b4f6e985bc8. Startup should be more reliable now.

**Comment by nylonee** [comment]
Leaving this open as the latest version of hangups is not yet compatible with the bot.
