### ISSUE TITLE
Subscribe plugin error: sre_constants.error: nothing to repeat

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#377]
Getting this error a lot, I'm assuming it's every time plugins.subscribe. _handle_keyword runs.

```
03:31:45 ERROR handlers: message: plugins.subscribe._handle_keyword : coroutine
Traceback (most recent call last):
  File "/root/hangoutsbot/hangoutsbot/hangupsbot/handlers.py", line 256, in run_pluggable_omnibus
    yield from function(*_passed)
  File "/root/hangoutsbot/hangoutsbot/hangupsbot/plugins/subscribe.py", line 43, in _handle_keyword
    if re.search(regexphrase, event.text, re.IGNORECASE):
  File "/usr/local/lib/python3.4/re.py", line 170, in search
    return _compile(pattern, flags).search(string)
  File "/usr/local/lib/python3.4/re.py", line 294, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/lib/python3.4/sre_compile.py", line 568, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/lib/python3.4/sre_parse.py", line 760, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/local/lib/python3.4/sre_parse.py", line 370, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/local/lib/python3.4/sre_parse.py", line 579, in _parse
    raise error("nothing to repeat")
sre_constants.error: nothing to repeat
```

**Comment by endofline** [comment]
Kindly provide your actual search token?

**Comment by endofline** [comment]
You might want to consider upgrading your pattern-matching to this: https://github.com/hangoutsbot/hangoutsbot/blob/staging/hangupsbot/plugins/autoreply.py#L105 - it's less fragile than `\b<word>\b`
