### ISSUE TITLE
Error with installation (ImportError: cannot import name 'IncompleteRead')

### ISSUE THREAD

**Issue by ManuCart** [hangoutsbot/hangoutsbot#416]
Hello,

I have this error when I try to install hangoutsbot

````
 sudo pip3 install -r requirements.txt
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip3')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python3/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python3/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name 'IncompleteRead'
````

**Comment by timw077** [comment]
I got past this by doing some python bits.   

$ git clone https://github.com/tdryer/hangups.git
$ cd hangups/
$ git checkout 84c6a20a24bede2fa41ffd54fda510e453f080dc
Edit setup.py  comment out the enum34 line.   
$ pip3 install .

Then return to your install and try the pip install -r requirements.txt

I'm running python35, and enum34 is "included".  The enum34 module collides with the namespace.

**Comment by nylonee** [comment]
These two seem to be different issues, but thanks for your fix @timw077, I've updated a branch for using hangups on python3.5 [here](https://github.com/hangoutsbot/hangups/tree/python3.5).

@ManuCart Be sure that you're using the latest version of pip, also read this [thread](http://stackoverflow.com/questions/27341064/how-do-i-fix-importerror-cannot-import-name-incompleteread)
