### ISSUE TITLE
SlackRTM fails to recover from connection closed exception

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#446]
This is probably a mistake I made during the logging improvements, sadly, I am stuck home with the flu and no sleep, so I'm not going to even attempt to fix it today. If someone with more brainpower wants to take a crack at it, most appreciated.

```
Dec 09 20:20:53 machine hangupsbot[276]: INFO sinks.base_bot_request_handler: SimpleMessagePoster: sending segments: 21
Dec 09 20:20:53 machine hangupsbot[276]: INFO sinks.base_bot_request_handler: SimpleMessagePoster: sending segments: 21
Dec 09 20:24:11 machine hangupsbot[276]: INFO root: Connection lost!
Dec 09 20:26:01 machine hangupsbot[276]: ERROR plugins.slackrtm: WebSocketConnectionClosedException(Connection is already closed.)
Dec 09 20:26:01 machine hangupsbot[276]: Traceback (most recent call last):
Dec 09 20:26:01 machine hangupsbot[276]: File "/home/pst/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 1050, in run
Dec 09 20:26:01 machine hangupsbot[276]: replies = self._listener.rtm_read()
Dec 09 20:26:01 machine hangupsbot[276]: File "/home/pst/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 423, in rtm_read
Dec 09 20:26:01 machine hangupsbot[276]: return self.slack.rtm_read()
Dec 09 20:26:01 machine hangupsbot[276]: File "/usr/local/lib/python3.4/dist-packages/slackclient/_client.py", line 27, in rtm_read
Dec 09 20:26:01 machine hangupsbot[276]: json_data = self.server.websocket_safe_read()
Dec 09 20:26:01 machine hangupsbot[276]: File "/usr/local/lib/python3.4/dist-packages/slackclient/_server.py", line 109, in websocket_safe_read
Dec 09 20:26:01 machine hangupsbot[276]: data += "{}\n".format(self.websocket.recv())
Dec 09 20:26:01 machine hangupsbot[276]: File "/usr/local/lib/python3.4/dist-packages/websocket/_core.py", line 348, in recv
Dec 09 20:26:01 machine hangupsbot[276]: opcode, data = self.recv_data()
Dec 09 20:26:01 machine hangupsbot[276]: File "/usr/local/lib/python3.4/dist-packages/websocket/_core.py", line 365, in recv_data
Dec 09 20:26:01 machine hangupsbot[276]: opcode, frame = self.recv_data_frame(control_frame)
Dec 09 20:26:01 machine hangupsbot[276]: File "/usr/local/lib/python3.4/dist-packages/websocket/_core.py", line 378, in recv_data_frame
Dec 09 20:26:01 machine hangupsbot[276]: frame = self.recv_frame()
Dec 09 20:26:01 machine hangupsbot[276]: File "/usr/local/lib/python3.4/dist-packages/websocket/_core.py", line 410, in recv_frame
Dec 09 20:26:01 machine hangupsbot[276]: return self.frame_buffer.recv_frame()
Dec 09 20:26:01 machine hangupsbot[276]: File "/usr/local/lib/python3.4/dist-packages/websocket/_abnf.py", line 312, in recv_frame
Dec 09 20:26:01 machine hangupsbot[276]: self.recv_header()
Dec 09 20:26:01 machine hangupsbot[276]: File "/usr/local/lib/python3.4/dist-packages/websocket/_abnf.py", line 261, in recv_header
Dec 09 20:26:01 machine hangupsbot[276]: header = self.recv_strict(2)
Dec 09 20:26:01 machine hangupsbot[276]: File "/usr/local/lib/python3.4/dist-packages/websocket/_abnf.py", line 346, in recv_strict
Dec 09 20:26:01 machine hangupsbot[276]: bytes = self.recv(min(16384, shortage))
Dec 09 20:26:01 machine hangupsbot[276]: File "/usr/local/lib/python3.4/dist-packages/websocket/_core.py", line 479, in _recv
Dec 09 20:26:01 machine hangupsbot[276]: return recv(self.sock, bufsize)
Dec 09 20:26:01 machine hangupsbot[276]: File "/usr/local/lib/python3.4/dist-packages/websocket/_socket.py", line 89, in recv
Dec 09 20:26:01 machine hangupsbot[276]: raise WebSocketConnectionClosedException("Connection is already closed.")
Dec 09 20:26:01 machine hangupsbot[276]: websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
Dec 09 20:26:01 machine hangupsbot[276]: INFO plugins.slackrtm: started RTM connection for SlackRTM thread <SlackRTMThread(SlackRTM:ebres, started daemon 140606794614528)>
Dec 09 20:26:01 machine hangupsbot[276]: ERROR asyncio: Future exception was never retrieved
Dec 09 20:26:01 machine hangupsbot[276]: future: <Future finished exception=gaierror(-3, 'Temporary failure in name resolution')>
Dec 09 20:26:01 machine hangupsbot[276]: Traceback (most recent call last):
Dec 09 20:26:01 machine hangupsbot[276]: File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
Dec 09 20:26:01 machine hangupsbot[276]: result = self.fn(*self.args, **self.kwargs)
Dec 09 20:26:01 machine hangupsbot[276]: File "/usr/lib/python3.4/socket.py", line 533, in getaddrinfo
Dec 09 20:26:01 machine hangupsbot[276]: for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Dec 09 20:26:01 machine hangupsbot[276]: socket.gaierror: [Errno -3] Temporary failure in name resolution
Dec 09 20:26:01 machine hangupsbot[276]: ERROR asyncio: Future exception was never retrieved
Dec 09 20:26:01 machine hangupsbot[276]: future: <Future finished exception=gaierror(-3, 'Temporary failure in name resolution')>
Dec 09 20:26:01 machine hangupsbot[276]: Traceback (most recent call last):
Dec 09 20:26:01 machine hangupsbot[276]: File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
Dec 09 20:26:01 machine hangupsbot[276]: result = self.fn(*self.args, **self.kwargs)
Dec 09 20:26:01 machine hangupsbot[276]: File "/usr/lib/python3.4/socket.py", line 533, in getaddrinfo
Dec 09 20:26:01 machine hangupsbot[276]: for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Dec 09 20:26:01 machine hangupsbot[276]: socket.gaierror: [Errno -3] Temporary failure in name resolution
Dec 09 20:26:01 machine hangupsbot[276]: ERROR asyncio: Future exception was never retrieved
Dec 09 20:26:01 machine hangupsbot[276]: future: <Future finished exception=gaierror(-2, 'Name or service not known')>
Dec 09 20:26:01 machine hangupsbot[276]: Traceback (most recent call last):
Dec 09 20:26:01 machine hangupsbot[276]: File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
Dec 09 20:26:01 machine hangupsbot[276]: result = self.fn(*self.args, **self.kwargs)
Dec 09 20:26:01 machine hangupsbot[276]: File "/usr/lib/python3.4/socket.py", line 533, in getaddrinfo
Dec 09 20:26:01 machine hangupsbot[276]: for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Dec 09 20:26:01 machine hangupsbot[276]: socket.gaierror: [Errno -2] Name or service not known
Dec 09 20:26:01 machine hangupsbot[276]: INFO root: list_conversations: 187 from permamem, 48 from hangups - discrepancies: none
Dec 09 20:26:04 machine hangupsbot[276]: ERROR plugins.slackrtm: SlackRTMThread: unhandled exception: [Errno 104] Connection reset by peer
Dec 09 20:26:04 machine hangupsbot[276]: Traceback (most recent call last):
Dec 09 20:26:04 machine hangupsbot[276]: File "/home/pst/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 1050, in run
Dec 09 20:26:04 machine hangupsbot[276]: replies = self._listener.rtm_read()
Dec 09 20:26:04 machine hangupsbot[276]: File "/home/pst/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 423, in rtm_read
Dec 09 20:26:04 machine hangupsbot[276]: return self.slack.rtm_read()
Dec 09 20:26:04 machine hangupsbot[276]: File "/usr/local/lib/python3.4/dist-packages/slackclient/_client.py", line 27, in rtm_read
Dec 09 20:26:04 machine hangupsbot[276]: json_data = self.server.websocket_safe_read()
Dec 09 20:26:04 machine hangupsbot[276]: File "/usr/local/lib/python3.4/dist-packages/slackclient/_server.py", line 109, in websocket_safe_read
Dec 09 20:26:04 machine hangupsbot[276]: data += "{}\n".format(self.websocket.recv())
Dec 09 20:26:04 machine hangupsbot[276]: File "/usr/local/lib/python3.4/dist-packages/websocket/_core.py", line 348, in recv
Dec 09 20:26:04 machine hangupsbot[276]: opcode, data = self.recv_data()
Dec 09 20:26:04 machine hangupsbot[276]: File "/usr/local/lib/python3.4/dist-packages/websocket/_core.py", line 365, in recv_data
Dec 09 20:26:04 machine hangupsbot[276]: opcode, frame = self.recv_data_frame(control_frame)
Dec 09 20:26:04 machine hangupsbot[276]: File "/usr/local/lib/python3.4/dist-packages/websocket/_core.py", line 378, in recv_data_frame
Dec 09 20:26:04 machine hangupsbot[276]: frame = self.recv_frame()
Dec 09 20:26:04 machine hangupsbot[276]: File "/usr/local/lib/python3.4/dist-packages/websocket/_core.py", line 410, in recv_frame
Dec 09 20:26:04 machine hangupsbot[276]: return self.frame_buffer.recv_frame()
Dec 09 20:26:04 machine hangupsbot[276]: File "/usr/local/lib/python3.4/dist-packages/websocket/_abnf.py", line 312, in recv_frame
Dec 09 20:26:04 machine hangupsbot[276]: self.recv_header()
Dec 09 20:26:04 machine hangupsbot[276]: File "/usr/local/lib/python3.4/dist-packages/websocket/_abnf.py", line 261, in recv_header
Dec 09 20:26:04 machine hangupsbot[276]: header = self.recv_strict(2)
Dec 09 20:26:04 machine hangupsbot[276]: File "/usr/local/lib/python3.4/dist-packages/websocket/_abnf.py", line 346, in recv_strict
Dec 09 20:26:04 machine hangupsbot[276]: bytes = self.recv(min(16384, shortage))
Dec 09 20:26:04 machine hangupsbot[276]: File "/usr/local/lib/python3.4/dist-packages/websocket/_core.py", line 479, in _recv
Dec 09 20:26:04 machine hangupsbot[276]: return recv(self.sock, bufsize)
Dec 09 20:26:04 machine hangupsbot[276]: File "/usr/local/lib/python3.4/dist-packages/websocket/_socket.py", line 77, in recv
Dec 09 20:26:04 machine hangupsbot[276]: bytes = sock.recv(bufsize)
Dec 09 20:26:04 machine hangupsbot[276]: File "/usr/lib/python3.4/ssl.py", line 733, in recv
Dec 09 20:26:04 machine hangupsbot[276]: return self.read(buflen)
Dec 09 20:26:04 machine hangupsbot[276]: File "/usr/lib/python3.4/ssl.py", line 622, in read
Dec 09 20:26:04 machine hangupsbot[276]: v = self._sslobj.read(len or 1024)
Dec 09 20:26:04 machine hangupsbot[276]: ConnectionResetError: [Errno 104] Connection reset by peer
Dec 09 20:29:10 machine hangupsbot[276]: INFO root: Connection lost!
Dec 09 20:29:10 machine hangupsbot[276]: ERROR hangups.channel: Ran out of retries for long-polling request
Dec 09 20:29:10 machine hangupsbot[276]: INFO root: bot is exiting
```

**Comment by pleasantone** [comment]
I haven't yet reproduced this after 26 days of production operation, closing for now.

**Comment by thannemann** [comment]
@pleasantone had the following today

2016-01-26 12:31:51 INFO plugins.botalive: watermarking XXXXXXXXXXXXXXXX
2016-01-26 12:32:48 INFO root: Connection lost!
2016-01-26 12:33:56 INFO root: Connection lost!
2016-01-26 12:35:44 INFO root: Connection lost!
2016-01-26 12:37:45 INFO root: Connection lost!
2016-01-26 12:37:45 ERROR hangups.channel: Ran out of retries for long-polling request
2016-01-26 12:37:45 INFO root: bot is exiting

**Comment by nylonee** [comment]
I had this error too, I thought it was just me so I made the fix on my own branch. I'll pull my fix through to master

**Comment by DanielCasner** [comment]
I am getting a version of this error as well, running current master:
```
2016-02-25 23:48:38 INFO root: Connection lost!
2016-02-26 00:08:02 INFO root: Connection lost!
2016-02-26 00:09:29 INFO root: Connection lost!
2016-02-26 00:09:37 ERROR asyncio: Future exception was never retrieved
future: <Future finished exception=gaierror(-3, 'Temporary failure in name resolution')>
Traceback (most recent call last):
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.4/socket.py", line 530, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2016-02-26 00:12:22 INFO root: Connection lost!
2016-02-26 00:33:12 INFO root: Connection lost!
```
