### ISSUE TITLE
Logging output unicode error

### ISSUE THREAD

**Issue by cd334** [hangoutsbot/hangoutsbot#470]
I made an upstart service from hangoutsbot and started. In the /var/log/ logs the log file for hangoutbot is full with error messages.
When I start hangoutsbot with nohup way then in the log file there are no error.

Error messages:
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/__init__.py", line 980, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe1' in position 85: ordinal not in range(128)
Call stack:
  File "hangupsbot/hangupsbot.py", line 993, in <module>
    main()
  File "hangupsbot/hangupsbot.py", line 989, in main
    bot.run()
  File "hangupsbot/hangupsbot.py", line 164, in run
    loop.run_until_complete(self._client.connect())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 304, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_forever
    self._run_once()
  File "/usr/lib/python3.4/asyncio/base_events.py", line 1172, in _run_once
    handle._run()
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 292, in _wakeup
    self._step(value, None)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/usr/local/lib/python3.4/dist-packages/hangups/channel.py", line 204, in listen
    yield from self._longpoll_request()
  File "/usr/local/lib/python3.4/dist-packages/hangups/channel.py", line 355, in _longpoll_request
    yield from self._on_push_data(chunk)
  File "/usr/local/lib/python3.4/dist-packages/hangups/channel.py", line 385, in _on_push_data
    yield from self.on_message.fire(submission)
  File "/usr/local/lib/python3.4/dist-packages/hangups/event.py", line 50, in fire
    yield from gen
  File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 315, in _on_push_data
    yield from self.on_state_update.fire(state_update)
  File "/usr/local/lib/python3.4/dist-packages/hangups/event.py", line 50, in fire
    yield from gen
  File "/usr/local/lib/python3.4/dist-packages/hangups/conversation.py", line 433, in _on_state_update
    state_update.event_notification.event
  File "/usr/local/lib/python3.4/dist-packages/hangups/conversation.py", line 447, in _on_client_event
    yield from self.on_event.fire(conv_event)
  File "/usr/local/lib/python3.4/dist-packages/hangups/event.py", line 50, in fire
    yield from gen
  File "hangupsbot/hangupsbot.py", line 578, in _on_event
    event = ConversationEvent(self, conv_event)
  File "/home/cd334/hangoutsbot/hangupsbot/event.py", line 77, in __init__
    self.log()
  File "/home/cd334/hangoutsbot/hangupsbot/event.py", line 84, in log
    logger.log(self.emit_log, 'c/g/un: {}/{}/{}'.format(self.user_id.chat_id, self.user_id.gaia_id, self.user.full_name))
Message: 'c/g/un: 108115655551135491860/108115655551135491860/D\xe1niel Czig\xe1ny'

my upstart service conf file:
description "HO bot daemon"
author "asdf"

start on (local-filesystems and net-device-up IFACE!=lo)
stop on runlevel [016]

respawn
respawn limit 5 60

setuid asdf
env HOME=/home/asdf/
chdir /home/asdf/hangoutsbot/
exec python3 hangupsbot/hangupsbot.py

**Comment by pleasantone** [comment]
You forgot to set the LANG environment variable, if you don’t, python 3 uses ascii, not UTF-8.
For example, with english in the US,  LANG=en_US.UTF-8

**Comment by cd334** [comment]
@pleasantone can you help me how to change my locale setting to prevent this error? 
My locale:
LANG=en_US.UTF-8
LANGUAGE= 
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES=en_US.UTF-8
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by pleasantone** [comment]
What kind of linux distribution, and version, are you running?  Is it debian based?
I think you mentioned upstart, so I’ll assume ubuntu.

I tried “ubuntu system locale” and got this page: https://help.ubuntu.com/community/Locale <https://help.ubuntu.com/community/Locale>

**Comment by cd334** [comment]
I have the solution. To the service configuration you need the following line:
env LANG=en_US.UTF-8

Then no UnicodeEncodeError any more :)

**Comment by mugbya** [comment]
@cd334 @pleasantone 

```sh
➜  ~ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

```sh
➜  ~ python3
Python 3.5.2 (default, Oct 11 2016, 04:59:56)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
```

but The problem still exists, help

**Comment by mugbya** [comment]
ok ，I got it

在 logging handlers set encoding

```py
    "handlers": {
        "info_file_handler": {
            "class": "logging.handlers.RotatingFileHandler",
            "level": "INFO",
            "formatter": "simple",
            "filename": "info.log",
            "maxBytes": 10485760,
            "backupCount": 20,
            "encoding": "utf8"
        },
     }
```

**Comment by pleasantone** [comment]
Fwiw, you should not need that. I handle UTF-8 all the time. I suspect upstart strips LANG.
