### ISSUE TITLE
screengrab on ubuntu can't find phantomjs

### ISSUE THREAD

**Issue by HuXDK** [hangoutsbot/hangoutsbot#511]
I've installed phantomjs, and checked (running 1.9.0)
But when i call /bot screenshot <url> i get "phantomjs could not be started - is it installed?"

**Comment by nylonee** [comment]
Open the python interpreter and try these:
```
> from selenium import webdriver
> driver = webdriver.PhantomJS()
```

If that doesn't work, it's likely that your phantomjs environment variable isn't set correctly. See [this SO](http://stackoverflow.com/questions/13287490/is-there-a-way-to-use-phantomjs-in-python) for more details on how you could potentially remedy this.

**Comment by acondoriml** [comment]
Hi,

I setup my proxy and phantoms environments but the problems keeps,,
This is my error 

>>> from selenium import webdriver
>>> webdriver.PhantomJS('/usr/local/bin/phantomjs')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/phantomjs/webdriver.py", line 56, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 87, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 141, in start_session
    'desiredCapabilities': desired_capabilities,
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/errorhandler.py", line 165, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message:

# ****The following error was encountered while trying to retrieve the URL: http://127.0.0.1:3396/wd/hub/session

Connection to 127.0.0.1 failed.**
**
