### ISSUE TITLE
Failed to fetch PVT token

### ISSUE THREAD

**Issue by lrocket** [hangoutsbot/hangoutsbot#528]
i am getting the following error when i start hangoutsbot after i entered the URL i got from the cli output and copied the token from the page at the hangoutsbot prompt:

```
22:30:53 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): accounts.google.com
22:30:53 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): accounts.google.com
22:30:54 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.google.com
22:30:54 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.google.at
22:30:55 ERROR root: CLIENT: unrecoverable low-level error
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 183, in _initialize_chat
    connector=self._connector
  File "/usr/local/lib/python3.4/dist-packages/hangups/http_utils.py", line 51, in fetch
    raise exceptions.NetworkError(error_msg)
hangups.exceptions.NetworkError: Request connection error: Cannot connect to host talkgadget.google.com:443 ssl:True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./hangupsbot/hangupsbot.py", line 164, in run
    loop.run_until_complete(self._client.connect())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 237, in _step
    result = next(coro)
  File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 109, in connect
    initial_data = yield from self._initialize_chat()
  File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 189, in _initialize_chat
    .format(e))
hangups.exceptions.HangupsError: Failed to fetch PVT token: Request connection error: Cannot connect to host talkgadget.google.com:443 ssl:True
Client unexpectedly disconnected:
Failed to fetch PVT token: Request connection error: Cannot connect to host talkgadget.google.com:443 ssl:True
22:30:55 INFO root: Waiting 5 seconds...
22:31:00 INFO root: Trying to connect again (try 1 of 5)...
22:31:00 ERROR root: CLIENT: unrecoverable low-level error
```

i installed the bot according to the install instructions on raspbian jessie which already came with python 3.4.2.

**Comment by nylonee** [comment]
See #106, it looks like if the problem persists, you'll need to recompile python :/

**Comment by Sjo3rd** [comment]
Im having the same issue suddenly on a bot which was perfectly working.
Without any code change out of the blue i have the same errors

**Comment by Sjo3rd** [comment]
Seems to be connection problems of my server
