### ISSUE TITLE
Watermarking failed error

### ISSUE THREAD

**Issue by thannemann** [hangoutsbot/hangoutsbot#535]
ERROR plugins.botalive: WATERMARK FAILED FOR XXXXXXXXXXXXXXXXXXXXXXXXXXXX
Traceback (most recent call last):
 File "/home/XXX/hangoutsbot/hangupsbot/plugins/botalive.py", line 124, in update_next_conversation
   datetime.datetime.fromtimestamp(time.time()))
 File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 593, in updatewatermark
   .format(res_status))
hangups.exceptions.NetworkError: Unexpected status: ERROR_INVALID_REQUEST

......
......
.....

ERROR plugins.botalive: critical error threshold reached, clearing queue

I have quit the bot, and reloaded, rebooted the computer its running on, I have pulled any and all updates from staging.  Still happens.

**Comment by thannemann** [comment]
Just found the error in my memory file I had a group hangout that no longer existed. it was a hangout that was killed by not having a botkeeper in it. but the memory file still had the hangout listed.
