### ISSUE TITLE
Bot fails on start - ValueError: None is not a valid OffTheRecordStatus

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#546]
I'm getting this error when I attempt to start my bot:

```
06:49:53 ERROR root: CLIENT: unrecoverable low-level error
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/hangups/pblite.py", line 157, in parse
    p = field.parse(field_input)
  File "/usr/local/lib/python3.4/dist-packages/hangups/pblite.py", line 63, in parse
    return self._enum(input_)
  File "/usr/lib/python3.4/enum.py", line 222, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.4/enum.py", line 457, in __new__
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: None is not a valid OffTheRecordStatus

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/hangups/pblite.py", line 105, in parse
    res.append(self._field.parse(field_input))
  File "/usr/local/lib/python3.4/dist-packages/hangups/pblite.py", line 160, in parse
    format(name, e))
ValueError: Message field 'event_otr': None is not a valid OffTheRecordStatus

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/hangups/pblite.py", line 157, in parse
    p = field.parse(field_input)
  File "/usr/local/lib/python3.4/dist-packages/hangups/pblite.py", line 107, in parse
    raise ValueError('RepeatedField item: {}'.format(e))
ValueError: RepeatedField item: Message field 'event_otr': None is not a valid OffTheRecordStatus

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/hangups/pblite.py", line 105, in parse
    res.append(self._field.parse(field_input))
  File "/usr/local/lib/python3.4/dist-packages/hangups/pblite.py", line 160, in parse
    format(name, e))
ValueError: Message field 'event': RepeatedField item: Message field 'event_otr': None is not a valid OffTheRecordStatus

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/share/hangoutsbot/hangupsbot/hangupsbot.py", line 164, in run
    loop.run_until_complete(self._client.connect())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 109, in connect
    initial_data = yield from self._initialize_chat()
  File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 256, in _initialize_chat
    data_dict['ds:19'][0][3]
  File "/usr/local/lib/python3.4/dist-packages/hangups/pblite.py", line 107, in parse
    raise ValueError('RepeatedField item: {}'.format(e))
ValueError: RepeatedField item: Message field 'event': RepeatedField item: Message field 'event_otr': None is not a valid OffTheRecordStatus
Client unexpectedly disconnected:
RepeatedField item: Message field 'event': RepeatedField item: Message field 'event_otr': None is not a valid OffTheRecordStatus
06:49:53 INFO root: Waiting 5 seconds...
```

Bot was working when this error happened, I haven't touched the config or the account.

**Comment by ragtim** [comment]
I too had the same error message start happening in the last 24 hours.

**Comment by bayoumedic** [comment]
same here

**Comment by Natejt** [comment]
Just restarted the hangupsbot.service, getting the same error on login

**Comment by nylonee** [comment]
This error just popped up on a second bot of mine on the same server. Other bots on my server remain unaffected even after reboots.

**Comment by nylonee** [comment]
@tdryer would you happen to have any insights on this issue? I know it's for an old version of your hangups, does the new version offer a fix for this?

**Comment by vaindil** [comment]
Also having the same problem, same tracebacks.

**Comment by tdryer** [comment]
The newest version of hangups doesn't seem to be affected. Adding `UNKNOWN = None` to the `OffTheRecordStatus` enum in `schemas.py` might work around the problem.

**Comment by vaindil** [comment]
This fixed the problem for me. We seriously need to look into getting this
project to use the updated hangups library if at all possible.

Steven Hall

**Comment by alx** [comment]
I've just updated the requirements (including hangups) to fix this issue:

`pip3 install -r requirements.txt --upgrade`

**Comment by acondoriml** [comment]
Thank you @alx  your advice fixed the problem for me.

Cheers!
