### ISSUE TITLE
The forecast plugin cannot set the default wather location

### ISSUE THREAD

**Issue by cd334** [hangoutsbot/hangoutsbot#551]
@vigoren the /bot setweatherlocation <location> does not work. In the log there is only this line:
22:04:07 INFO event: len/tx: 33//bot setweatherlocation Budapest
22:04:07 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): maps.googleapis.com

No answer in the HO. 
The other two command working.

**Comment by vigoren** [comment]
@cd334 I just tested it quickly and it is working properly for me.

Just to clarify if you do /bot weather Budapest it loads the data correctly?

I would find that strange as both calls use the same function to get the location information.

Though looking at my code I am not properly handling potential timeout or connection error exceptions, which is what it sounds like is happening. I will make some changes to handle those better

**Comment by cd334** [comment]
@vigoren  /bot weather Budapest work correct.

**Comment by vigoren** [comment]
@cd334 the changes in my last commit (70f4b00af5925d485ed4015c42f4584a7208c555) should fix the issue you are having.

**Comment by cd334** [comment]
THX, i will test it if I have time.

**Comment by lglenden** [comment]
I am also seeing this problem.  Here is the stack trace I see:

20:47:28 ERROR commands: RUN: setweatherlocation
Traceback (most recent call last):
  File "/root/hangoutsbot/hangupsbot/commands/__init__.py", line 178, in run
    results = yield from func(bot, event, *args, **kwds)
  File "/root/hangoutsbot/hangupsbot/plugins/forecast.py", line 40, in setweatherlocation
    bot.memory.set_by_path(['conv_data', event.conv.id_], {})
  File "/root/hangoutsbot/hangupsbot/config.py", line 118, in set_by_path
    self.get_by_path(keys_list[:-1])[keys_list[-1]] = value
TypeError: 'NoneType' object does not support item assignment

**Comment by lglenden** [comment]
Replacing

```
    if not bot.memory.exists(["conv_data", event.conv.id_]):
        bot.memory.set_by_path(['conv_data', event.conv.id_], {})
```

with

```
    bot.initialise_memory(event.conv_id, "conv_data")
    #if not bot.memory.exists(["conv_data", event.conv.id_]):
    #    bot.memory.set_by_path(['conv_data', event.conv.id_], {})
```

fixed it for me.

**Comment by nylonee** [comment]
Interesting... That would imply that `conv_data` is not set prior to the weather call (see [L483](https://github.com/hangoutsbot/hangoutsbot/blob/master/hangupsbot/hangupsbot.py#L483), the code is similar to what is commented out, with the exception of also initializing `conv_data`)

Since `conv_data` is a critical component to several other plugins, I would suggest a fix that modifies the core hangoutsbot, rather than a plugin fix.

**Comment by langtall** [comment]
This issue is still present. Also the fix as presented by lglenden gives the same error.

**Comment by bobpaul** [comment]
This issue is still present but Iglenden's fix seems to work for me. I did restart hangoutsbot after editing plugins/forecast.py
