### ISSUE TITLE
Can't load telesync

### ISSUE THREAD

**Issue by fortiZde** [hangoutsbot/hangoutsbot#563]
Hey um running hangoutsbot in v2.7.8 and now got errors while starting:

```
02:24:08 ERROR plugins: EXCEPTION during plugin init: plugins.telesync
Traceback (most recent call last):
  File "/opt/hangoutsbot/hangupsbot/plugins/__init__.py", line 359, in load
    the_function(bot)
  File "/opt/hangoutsbot/hangupsbot/plugins/telesync/__init__.py", line 501, in _initialise
    loop.create_task(tg_bot.messageLoop())
AttributeError: 'TelegramBot' object has no attribute 'messageLoop'
```

Telesync is added to plugins and also added configurations for telesync:

```
  "telesync": {
    "admins": [
      "1337"
    ],
    "api_key": "Here is my API Key",
    "do_not_keep_photos": true,
    "enabled": true
  }
```

**Comment by fortiZde** [comment]
will be fixed!
https://github.com/hangoutsbot/hangoutsbot/pull/562
