### ISSUE TITLE
Sending images fails with 400: Bad Request

### ISSUE THREAD

**Issue by vaindil** [hangoutsbot/hangoutsbot#616]
Images are failing to be sent. Traceback is below, not sure what to make of it. Also not sure if I should post this on hangoutsbot/hangups or here, sorry.

```
17:00:06 ERROR root: CORO_SEND_MESSAGE: error sending [conv ID removed]
Traceback (most recent call last):
  File "/home/wazebot/wazebot/hangupsbot/hangupsbot.py", line 749, in coro_send_message
    otr_status=otr_status )
  File "/home/wazebot/wazebot/hangupsbot/hangups_conversation.py", line 162, in send_message
    image_id=image_id, otr_status=otr_status
  File "/usr/local/lib/python3.4/site-packages/hangups/client.py", line 431, in sendchatmessage
    res = yield from self._request('conversations/sendchatmessage', body)
  File "/usr/local/lib/python3.4/site-packages/hangups/client.py", line 327, in _request
    use_json=use_json
  File "/usr/local/lib/python3.4/site-packages/hangups/client.py", line 350, in _base_request
    data=data, connector=self._connector
  File "/usr/local/lib/python3.4/site-packages/hangups/http_utils.py", line 57, in fetch
    .format(res.status, res.reason)
hangups.exceptions.NetworkError: Request return unexpected status: 400: Bad Request
```

**Comment by vaindil** [comment]
The problem appears to have resolved itself.
