### ISSUE TITLE
_on_connect() missing one positional argument: 'initial_data'

### ISSUE THREAD

**Issue by mrjohnyhats** [hangoutsbot/hangoutsbot#622]
After cloning and starting the current version of hangupsbot, it gives me an error message:  `ERROR root: CLIENT: unrecoverable low-level error`, python also gives me another error message after the stack trace: `_on_connect() missing 1 required positional argument: 'initial_data'` where `_on_connect()` is a function defined in the `__main__.py` file in the hangups module. This issue might just be a bug in the hangups module itself, but I'm not too familiar with either repos. Here's the stack trace for the interested: 

`Traceback (most recent call last):
  File "hangupsbot.py", line 165, in run
    loop.run_until_complete(self._client.connect())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 234, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 102, in connect
    yield from self._listen_future
  File "/usr/lib/python3.4/asyncio/futures.py", line 386, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 287, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/usr/local/lib/python3.4/dist-packages/hangups/channel.py", line 209, in listen
    yield from self._longpoll_request()
  File "/usr/local/lib/python3.4/dist-packages/hangups/channel.py", line 338, in _longpoll_request
    yield from self._on_push_data(chunk)
  File "/usr/local/lib/python3.4/dist-packages/hangups/channel.py", line 359, in _on_push_data
    yield from self.on_connect.fire()
  File "/usr/local/lib/python3.4/dist-packages/hangups/event.py", line 50, in fire
    yield from gen
  File "/usr/local/lib/python3.4/dist-packages/hangups/event.py", line 48, in fire
    gen = observer(*args, **kwargs)`

**Comment by Terrance** [comment]
This was likely to do with the ancient fork of hangups we were using -- as of v3 we track upstream, so this hopefully shouldn't be an issue any more.
