### ISSUE TITLE
Unrecoverable low level error

### ISSUE THREAD

**Issue by Raptor123471** [hangoutsbot/hangoutsbot#654]
> 2016-11-04 18:17:04 INFO config: C:\Users\John\AppData\Local\hangupsbot\hangupsbot\config.json read
2016-11-04 18:17:04 INFO root: memory = C:\Users\John\AppData\Local\hangupsbot\hangupsbot\memory.json, failsafe = 3, delay = 1
2016-11-04 18:17:04 INFO root: creating memory file: C:\Users\John\AppData\Local\hangupsbot\hangupsbot\memory.json
2016-11-04 18:17:04 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): accounts.google.com
2016-11-04 18:17:05 INFO config: C:\Users\John\AppData\Local\hangupsbot\hangupsbot\memory.json write 0.0005002021789550781
2016-11-04 18:17:20 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.google.com
2016-11-04 18:17:26 ERROR root: CLIENT: unrecoverable low-level error
Traceback (most recent call last):
  File "C:\Users\John\Documents\New folder\hangupsbot\hangupsbot.py", line 164, in run
    loop.run_until_complete(self._client.connect())
  File "C:\Users\John\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 387, in run_until_complete
    return future.result()
  File "C:\Users\John\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\John\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "C:\Users\John\AppData\Local\Programs\Python\Python35\lib\site-packages\hangups\client.py", line 122, in connect
    yield from self._listen_future
  File "C:\Users\John\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\John\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 296, in _wakeup
    future.result()
  File "C:\Users\John\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\John\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\John\AppData\Local\Programs\Python\Python35\lib\site-packages\hangups\channel.py", line 198, in listen
    yield from self._fetch_channel_sid()
  File "C:\Users\John\AppData\Local\Programs\Python\Python35\lib\site-packages\hangups\channel.py", line 244, in _fetch_channel_sid
    'ctype': 'hangouts',  # client type
  File "C:\Users\John\AppData\Local\Programs\Python\Python35\lib\site-packages\hangups\http_utils.py", line 36, in fetch
    ), CONNECT_TIMEOUT)
  File "C:\Users\John\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 392, in wait_for
    return fut.result()
  File "C:\Users\John\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\John\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\John\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\client.py", line 198, in _request
    proxy=proxy, proxy_auth=proxy_auth, timeout=timeout)
  File "C:\Users\John\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\client_reqrep.py", line 79, in __init__
    url2 = url.with_query(params)
  File "C:\Users\John\AppData\Local\Programs\Python\Python35\lib\site-packages\yarl\__init__.py", line 607, in with_query
    for k, v in query.items())
  File "C:\Users\John\AppData\Local\Programs\Python\Python35\lib\site-packages\yarl\__init__.py", line 607, in <genexpr>
    for k, v in query.items())
  File "yarl\_quoting.pyx", line 46, in yarl._quoting._quote (yarl/_quoting.c:1384)
TypeError: Argument should be str
2016-11-04 18:17:26 INFO root: Waiting 5 seconds...
2016-11-04 18:17:31 INFO root: Trying to connect again (try 1 of 5)...

**Comment by Raptor123471** [comment]
This issue only occurs on Windows

**Comment by DanGe42** [comment]
I resolved this by locking the aiohttp version in the requirements.txt file, e.g. `aiohttp>=1.0,<1.1`

There's some discussion about the aiohttp change in their issue tracker https://github.com/KeepSafe/aiohttp/issues/1364

**Comment by cd334** [comment]
After the update the bot to the latest master it won't started. The solution was the change in requirements.txt aiohttp>=1.0,<1.1 after the pip3 upgrade it worked again.
