### ISSUE TITLE
KeyError: 'ds:7' in hangups

### ISSUE THREAD

**Issue by Raptor123471** [hangoutsbot/hangoutsbot#659]
[error.txt](https://github.com/hangoutsbot/hangoutsbot/files/582231/error.txt)

Log included in text document.

**Comment by nylonee** [comment]
Getting the same error here:
```
18:27:34 INFO config: /root/.local/share/hangupsbot/config.json read
18:27:34 INFO root: memory = /root/.local/share/hangupsbot/memory.json, failsafe = 3, delay = 1
18:27:34 INFO config: /root/.local/share/hangupsbot/memory.json read
18:27:34 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): accounts.google.com
18:27:34 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.google.com
18:27:34 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.google.com.sg
18:27:35 ERROR root: CLIENT: unrecoverable low-level error
Traceback (most recent call last):
  File "/usr/local/share/hangupsenv/lib/python3.5/site-packages/hangups/client.py", line 227, in _initialize_chat
    self._api_key = data_dict['ds:7'][0][2]
KeyError: 'ds:7'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hangoutsbot/hangupsbot/hangupsbot.py", line 164, in run
    loop.run_until_complete(self._client.connect())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/share/hangupsenv/lib/python3.5/site-packages/hangups/client.py", line 109, in connect
    initial_data = yield from self._initialize_chat()
  File "/usr/local/share/hangupsenv/lib/python3.5/site-packages/hangups/client.py", line 241, in _initialize_chat
    'value: {}'.format(e))
hangups.exceptions.HangupsError: Failed to get initialize chat value: 'ds:7'
Client unexpectedly disconnected:
Failed to get initialize chat value: 'ds:7'
```

This appears to be a hangups issue, @tdryer might know more.

**Comment by JosephBlock** [comment]
within hangups/client.py
change
`CHAT_INIT_PARAMS = {
    'prop': 'aChromeExtension',
    'fid': 'gtn-roster-iframe-id',
    'ec': '["ci:ec",true,true,false]',
    'pvt': None,  # Populated later
}`
to
`CHAT_INIT_PARAMS = {
    'prop': 'StartPage',
    'fid': 'gtn-roster-iframe-id',
    'ec': '["ci:ec",true,true,false]',
    'pvt': None,  # Populated later
}`

**Comment by JosephBlock** [comment]
@nylonee @Raptor123471 https://github.com/hangoutsbot/hangups/pull/5/files

**Comment by Teleken** [comment]
Thanks guys for fixing this so quickly!

**Comment by lindi200000** [comment]
Yes thx for fix. 
https://github.com/hangoutsbot/hangups/pull/5/files works perfect :)

**Comment by csansone** [comment]
Not to be a parrot, but thanks so much for the quick fix, it is greatly appreciated!

**Comment by azack** [comment]
```pip3 install requirements.txt --upgrade``` may also help.

**Comment by 1Z4N4G1** [comment]
I've got this error these days.

 pip3 install -r requirements.txt --upgrade

doesn't work for me...

**Comment by OllieTerrance** [comment]
Another possible response change, see #925 and tdryer/hangups#413.

**Comment by 1Z4N4G1** [comment]
Run `git checkout v3.0` and then `pip3 install -r requirements.txt` works!
thank you @OllieTerrance
