### ISSUE TITLE
Image uploads failing from Hangouts > Slack

### ISSUE THREAD

**Issue by filemaniac** [hangoutsbot/hangoutsbot#662]
I've updated from master to v2.7.10, but this also happened in a previous version too.  I updated today in hopes this would fix the problem, but it has not.  Images from Slack > Hangouts works fine.  Here is what I am seeing in the console and in the log (nothing more shows up in hangupsbot.log even with verbose logging).  Numbers and names changed, 2 uploads attempted for this log output:

23:14:18 INFO event: eid/dt: 89-GgBOTGjs8LFDTzSZ_mD/2016-11-13 23:14:18
23:14:18 INFO event: cid/cn: <HO_ID>/<HO_NAME>
23:14:18 INFO event: c/g/un: <UID>/<UID>/<SLACK_CHANNEL_NAME>
23:14:18 INFO event: len/tx: 0/

23:14:49 INFO event: eid/dt: 89-GgBOTGjs8LFDXlIMGOV/2016-11-13 23:14:49
23:14:49 INFO event: cid/cn: <HO_ID>/<HO_NAME>
23:14:49 INFO event: c/g/un: <UID>/<UID>/<SLACK_CHANNEL_NAME>
23:14:49 INFO event: len/tx: 0/

**Comment by JosephBlock** [comment]
Make sure to also update with requirements.txt and restart bot

**Comment by filemaniac** [comment]
Unfortunately, that made just things worse and the bot won't even run now.  My requirements.txt matches the master.

Console output:
23:57:43 INFO config: /root/.local/share/hangupsbot/config.json read
23:57:43 INFO root: memory = /root/.local/share/hangupsbot/memory.json, failsafe = 3, delay = 1
23:57:43 INFO config: /root/.local/share/hangupsbot/memory.json read
23:57:43 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): accounts.google.com
23:57:44 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.google.com
Traceback (most recent call last):
  File "hangupsbot.py", line 997, in <module>
    main()
  File "hangupsbot.py", line 993, in main
    bot.run()
  File "hangupsbot.py", line 153, in run
    sinks.start(self)
  File "/root/hangoutsbot/hangupsbot/sinks/__init__.py", line 74, in start
    "json-rpc")
  File "/root/hangoutsbot/hangupsbot/sinks/__init__.py", line 148, in aiohttp_start
    RequestHandler.addroutes(app.router)
  File "/root/hangoutsbot/hangupsbot/sinks/base_bot_request_handler.py", line 135, in addroutes
    router.add_route("POST", "/{convid}", self.adapter_do_POST)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/web_urldispatcher.py", line 824, in add_route
    resource = self.add_resource(path, name=name)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/web_urldispatcher.py", line 819, in add_resource
    self._reg_resource(resource)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/web_urldispatcher.py", line 763, in _reg_resource
    raise RuntimeError("Cannot register a resource into "
RuntimeError: Cannot register a resource into frozen router.
Exception ignored in: <bound method _UnixSelectorEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/base_events.py", line 361, in __del__
  File "/usr/lib/python3.4/asyncio/unix_events.py", line 57, in close
  File "/usr/lib/python3.4/asyncio/unix_events.py", line 138, in remove_signal_handler
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object

**Comment by JosephBlock** [comment]
https://github.com/hangoutsbot/hangoutsbot/pull/655 should fix that i believe

**Comment by filemaniac** [comment]
That fixed it.  Now that it's working again, image uploads from Hangouts > Slack are working too.  Thank you @JosephBlock!
