### ISSUE TITLE
Crash at start.

### ISSUE THREAD

**Issue by captainmoha** [hangoutsbot/hangoutsbot#663]
My bot is crashing at start. I am on the latest master branch and all libs are updated.

`
15:09:31 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.google.com
Traceback (most recent call last):
  File "./hangupsbot.py", line 997, in <module>
    main()
  File "./hangupsbot.py", line 993, in main
    bot.run()
  File "./hangupsbot.py", line 153, in run
    sinks.start(self)
  File "/home/ubuntu/workspace/repos/hangoutsbot/hangupsbot/sinks/__init__.py", line 74, in start
    "json-rpc")
  File "/home/ubuntu/workspace/repos/hangoutsbot/hangupsbot/sinks/__init__.py", line 148, in aiohttp_start
    RequestHandler.addroutes(app.router)
  File "/home/ubuntu/workspace/repos/hangoutsbot/hangupsbot/sinks/base_bot_request_handler.py", line 135, in addroutes
    router.add_route("POST", "/{convid}", self.adapter_do_POST)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/web_urldispatcher.py", line 824, in add_route
    resource = self.add_resource(path, name=name)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/web_urldispatcher.py", line 819, in add_resource
    self._reg_resource(resource)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/web_urldispatcher.py", line 763, in _reg_resource
    raise RuntimeError("Cannot register a resource into "
RuntimeError: Cannot register a resource into frozen router.
Exception ignored in: <bound method _UnixSelectorEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/base_events.py", line 361, in __del__
  File "/usr/lib/python3.4/asyncio/unix_events.py", line 57, in close
  File "/usr/lib/python3.4/asyncio/unix_events.py", line 138, in remove_signal_handler
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
`

**Comment by JosephBlock** [comment]
See https://github.com/hangoutsbot/hangoutsbot/pull/655 for fix

**Comment by captainmoha** [comment]
@JosephBlock That did it. Thanks!
