### ISSUE TITLE
aiohttp.errors.HttpProxyError: 503, message='Service Unavailable'

### ISSUE THREAD

**Issue by acondoriml** [hangoutsbot/hangoutsbot#676]
Hi folks,

I have a proxy on my net. I add this to my code:

first I changed this in /usr/local/lib/python3.4/dist-packages/hangups/client.py

```
        #proxy = os.environ.get('HTTP_PROXY')
        proxy = os.environ.get('http_proxy')
```

And add this in hangupsbot.py

```
import os
os.environ["http_proxy"] = "http://proxy.myproxy.com:80"
```

And now I have this error:

```
Traceback (most recent call last):
  File "hangupsbot.py", line 171, in run
    loop.run_until_complete(self._client.connect())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 280, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 111, in connect
    initial_data = yield from self._initialize_chat()
  File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 185, in _initialize_chat
    connector=self._connector
  File "/usr/local/lib/python3.4/dist-packages/hangups/http_utils.py", line 36, in fetch
    ), CONNECT_TIMEOUT)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 386, in wait_for
    return fut.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 280, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/client.py", line 165, in _request
    conn = yield from self._connector.connect(req)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/connector.py", line 306, in connect
    yield from self._create_connection(req)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/connector.py", line 749, in _create_connection
    transport, proto = yield from super()._create_connection(req)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/connector.py", line 583, in _create_connection
    transport, proto = yield from self._create_proxy_connection(req)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/connector.py", line 683, in _create_proxy_connection
    raise HttpProxyError(code=resp.status, message=resp.reason)
aiohttp.errors.HttpProxyError: 503, message='Service Unavailable'
Client unexpectedly disconnected:
503, message='Service Unavailable'
09:19:24 INFO root: Waiting 20 seconds...
09:19:44 INFO root: Trying to connect again (try 4 of 5)...
09:19:44 ERROR asyncio: Unclosed client session

```

Any body Know if I need to add/change any date more?

Thanks a lot!

**Comment by iBotPeaches** [comment]
When I retrieved this error I found Google had blocked me and I had to enter some captcha to return service. So I used `links2`, visited google and entered the captcha then my bots would start again.

It redirected me to ipv6.google.com so found it was strange that it kept favoring v6.
