### ISSUE TITLE
No email received during first-run.

### ISSUE THREAD

**Issue by finnito** [hangoutsbot/hangoutsbot#683]
Hello!

I have done the following:
`git clone https://github.com/hangoutsbot/hangoutsbot`
`virtualenv -p /usr/bin/python3.4 py3env`
`source py3env/bin/activate`
`apt-get install python3-pip`
`pip install -r requirements.txt`
`python3 hangupsbot/hangupsbot.py -d`

Except no email comes through when I try log into my Google Account on the first run.
I've been looking at [this issue](https://github.com/tdryer/hangups/issues/260) and have been able to obtain my oauth_id but am not sure where to use it.

And here's my log when I attempt to login but no code gets emailed through:

```2016-12-12 21:23:10 ERROR root: LOGIN FAILED
Traceback (most recent call last):
  File "/root/hangoutsbot/hangoutsbot/py3env/lib/python3.4/site-packages/hangups/auth.py", line 132, in get_auth
    raise GoogleAuthError("Refresh token not found")
hangups.auth.GoogleAuthError: Refresh token not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/hangoutsbot/hangoutsbot/py3env/lib/python3.4/site-packages/hangups/auth.py", line 183, in submit_form
    form.select(selector)[0]['value'] = value
IndexError: list index out of range

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "hangupsbot/hangupsbot.py", line 137, in login
    cookies = hangups.auth.get_auth_stdin(cookies_path)
  File "/root/hangoutsbot/hangoutsbot/py3env/lib/python3.4/site-packages/hangups/auth.py", line 64, in get_auth_stdin
    return get_auth(CredentialsPrompt(), refresh_token_cache)
  File "/root/hangoutsbot/hangoutsbot/py3env/lib/python3.4/site-packages/hangups/auth.py", line 138, in get_auth
    session, credentials_prompt
  File "/root/hangoutsbot/hangoutsbot/py3env/lib/python3.4/site-packages/hangups/auth.py", line 227, in _get_authorization_code
    {VERIFICATION_CODE_SELECTOR: verfification_code}
  File "/root/hangoutsbot/hangoutsbot/py3env/lib/python3.4/site-packages/hangups/auth.py", line 186, in submit_form
    'Failed to find input {!r} in form'.format(selector)
hangups.auth.GoogleAuthError: Failed to find input '#totpPin' in form
2016-12-12 21:23:10 ERROR root: Valid login required, exiting
```

Any help would be appreciated.

**Comment by pleasantone** [comment]
Looks like two factor authentication may be broken

**Comment by MTRNord** [comment]
Or maybe try to Login trough Lynx first. That did work for me.

**Comment by nylonee** [comment]
A suggested fix from #717 is to turn on debugging mode (run `python hangupsbot.py -d`). Any confirmation that this fixes the issue would be appreciated

**Comment by vaindil** [comment]
If anyone else has this problem, note that you DO NOT use an app-specific password. I was trying to do that, took me way too long to realize that's wrong. -_-

**Comment by Bogwitch** [comment]
I can confirm that accessing the mailbox from lynx before makes the authentication successful, I had previously copied the cookie to cookie.json so this might have an influence.

**Comment by nylonee** [comment]
Just stumbled upon this error myself. Appending -d did not work, logging in through lynx did. Thanks for help

**Comment by nylonee** [comment]
**Known possible workarounds**
- Log in via lynx onto the remote server and complete the verification questions
- Log in via ssh tunnel and complete the verification questions
- (Untested) Log into hangoutsbot on a local server and copy the cookies file to the remote server

**Comment by MTRNord** [comment]
Possible workaround can be: 
1. Login on your known normal PC to the bot account
2. Open https://accounts.google.com/displayunlockcaptcha
3. Start the Bot on the server. It should now show you the captcha on your PC and not at the server. 

This is a google magic link means it is normaly used to unblock devies that google thinks of as a bad device. It should route the captcha to the device where this link is open at.

**Comment by donkawechico** [comment]
I tested MTRNord's workaround and it fixed my issue! Thanks!

**Comment by guillain** [comment]
Hello,

I've the same "original" issue but the workarround doesn't for me.

Before to apply the workarround (#2), I was prompted to enter the "Verification code", after not with the same error logs:
````
# python3.5 hangupsbot/hangupsbot.py
04:31:22 INFO config: /root/.local/share/hangupsbot/config.json read
04:31:22 INFO root: memory = /root/.local/share/hangupsbot/memory.json, failsafe = 3, delay = 1
04:31:22 INFO config: /root/.local/share/hangupsbot/memory.json read
04:31:22 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): accounts.google.com
Sign in with your Google account:
Email: guillainbot@gmail.com
Password:
04:31:35 ERROR root: LOGIN FAILED
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/hangups/auth.py", line 132, in get_auth
    raise GoogleAuthError("Refresh token not found")
hangups.auth.GoogleAuthError: Refresh token not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/hangups/auth.py", line 231, in _get_authorization_code
    return browser.get_cookie('oauth_code')
  File "/usr/lib/python3.5/site-packages/hangups/auth.py", line 199, in get_cookie
    return self._session.cookies[name]
  File "/usr/lib/python3.5/site-packages/requests/cookies.py", line 282, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/lib/python3.5/site-packages/requests/cookies.py", line 340, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='oauth_code', domain=None, path=None"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hangupsbot/hangupsbot.py", line 137, in login
    cookies = hangups.auth.get_auth_stdin(cookies_path)
  File "/usr/lib/python3.5/site-packages/hangups/auth.py", line 64, in get_auth_stdin
    return get_auth(CredentialsPrompt(), refresh_token_cache)
  File "/usr/lib/python3.5/site-packages/hangups/auth.py", line 138, in get_auth
    session, credentials_prompt
  File "/usr/lib/python3.5/site-packages/hangups/auth.py", line 233, in _get_authorization_code
    raise GoogleAuthError('Authorization code cookie not found')
hangups.auth.GoogleAuthError: Authorization code cookie not found
04:31:35 ERROR root: Valid login required, exiting
```

Thanks for your support !

**Comment by guillain** [comment]
Yep,

I've solved my auth issue with the manual login explained in these threads:
* https://github.com/hangoutsbot/hangoutsbot/issues/711
* https://github.com/tdryer/hangups/issues/350#issuecomment-323553771

Have a nice weekend ;-)
