### ISSUE TITLE
NameError: name 'bot' is not defined

### ISSUE THREAD

**Issue by azack** [hangoutsbot/hangoutsbot#766]
I think introduced by 943f83c65c8adec0c16cbd1aefa78955bd47012c

```
2017-03-03 18:44:55 ERROR plugins.slackrtm: error in handleCommands: <class 'NameError'>(name 'bot' is not defined)
Traceback (most recent call last):
  File "/home/hangupsbot/hangupsbot-official/hangupsbot/plugins/slackrtm.py", line 1151, in handle_reply
    self.handleCommands(msg)
  File "/home/hangupsbot/hangupsbot-official/hangupsbot/plugins/slackrtm.py", line 713, in handleCommands
    hangoutname = bot.conversations.get_name(c, truncate=False)
NameError: name 'bot' is not defined
```

**Comment by MTRNord** [comment]
should be this.bot right?(was just looking at that commit)

**Comment by endofline** [comment]
i require a test of latest staging copy as I'm not personally running this plugin - the latest commit should fix the referencing error

**Comment by azack** [comment]
@endofline This looks good in staging so far, thank you.

**Comment by endofline** [comment]
i'm closing this issue since there seems to be no further reports of problems with the plugin. if you encounter anything new, feel free to re-open this issue; create a new one; or update #765
