### ISSUE TITLE
Doesn't respond..

### ISSUE THREAD

**Issue by thesteed** [hangoutsbot/hangoutsbot#774]
I've configured the bot and it loads, doesn't produce any errors, but it doesn't respond to messages at all.

When I start the bot it shows that it loads and sees all the conversations and contacts, it doesn't give any errors but if I message it and say "/bot help" or any other command it doesn't respond and the console doesn't output any messages. What am I doing wrong?

More specifics:
Plugins: just the defaults after cloning it
User: our company uses gmail, so it uses an account: blah@customdomain.com to login
I open a conversation in gmail w/ the user and then send the message "/bot help" w/out quotes, nothing happens

**Comment by thesteed** [comment]
Also side note, when it completely ignores the plugins listed in the config.json file. I tried adding some of the plugins but it never even attempts to load them.

**Comment by thesteed** [comment]
Also I checked all the files/logs in ~/.local/share/hangupsbot/
and ran with -d argument, no errors anywhere.

The memory.json correctly has all the users and info in it.

**Comment by thesteed** [comment]
looks like it might be related to hangups package

**Comment by JosephBlock** [comment]
Does the bot show it's still running? It should respond with /bot ping.

**Comment by JosephBlock** [comment]
Can you also share `hangups -v`

**Comment by thesteed** [comment]
I can't get hangups to install. after removing all the packages and trying to install the specific versions it depends on I now get this:

`asteed@asteed-linux:~/software/hangoutsbot$ hangups -version
Traceback (most recent call last):
  File "/usr/local/bin/hangups", line 11, in <module>
    load_entry_point('hangups==0.4.2', 'console_scripts', 'hangups')()
  File "/home/asteed/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/asteed/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/home/asteed/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/home/asteed/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/hangups-0.4.2-py3.5.egg/hangups/__init__.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/hangups-0.4.2-py3.5.egg/hangups/client.py", line 3, in <module>
  File "/usr/local/lib/python3.5/dist-packages/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/usr/local/lib/python3.5/dist-packages/asyncio/base_events.py", line 18, in <module>
    import concurrent.futures
  File "/usr/local/lib/python3.5/dist-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/usr/local/lib/python3.5/dist-packages/concurrent/futures/_base.py", line 357
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax
`

**Comment by JosephBlock** [comment]
Did you install with `pip3 install -r requirements.txt`? That should have everything required to run.

**Comment by thesteed** [comment]
yes I did, I even tried it on another server that was a fresh install w/out any other packages installed and it gives me the same result. This is on ubuntu 16.04

**Comment by JosephBlock** [comment]
If that does not work, please install python3.4

**Comment by thesteed** [comment]
I got hangups to work, it is: hangups 0.2.10.1

But I'm still back at square one w/ the bot. When I start it, it doesn't give me any errors, but it seems to load all the details correctly:

13:04:37 INFO permamem: new user FirstName LastName (1166886158088133752071)
13:04:37 INFO permamem: user 1166886158088133752071 updated FirstName LastName
13:04:37 INFO permamem: loading 8 conversations from hangups
13:04:37 INFO permamem: new conv sam theman (UgygtcEoCcmU22snbqF4AaABAagB5pX-xCg)

oh well I give up

**Comment by thannemann** [comment]
so it appears it is connecting with google, and it is loading the conversations, 
Have you read : https://github.com/hangoutsbot/hangoutsbot/blob/master/INSTALL.md#initial-configuration

Have you sent the initial command /bot iamspartacus this makes you an admin 

you do not edit the config.json in your hangouts directory, you need to edit the one in the /<username>/.local/share/hangupsbot/

**Comment by nylonee** [comment]
Could you check if the messages are going into invites on the bot's end? The bot is unable to read any messages that are going into invites.

**Comment by nylonee** [comment]
If you still require assistance with this, feel free to continue commenting, otherwise, I'm closing this issue now.

**Comment by thesteed** [comment]
I appreciate the help, but we ended up switching to slack :/
