### ISSUE TITLE
Failed to load JavaScript: No token definition matched

### ISSUE THREAD

**Issue by vaindil** [hangoutsbot/hangoutsbot#778]
Trying to start my bot just now and I'm getting the below stack trace. Can't get it to run.

```
ERROR root: CLIENT: unrecoverable low-level error
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/hangups/javascript.py", line 20, in loads
    return _PARSER.parse(string)
  File "/usr/local/lib/python3.4/site-packages/purplex/parse.py", line 220, in parse
    raise StartSymbolNotReducedError(self.START)
purplex.exception.StartSymbolNotReducedError: Consumed all input without reducing e

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/hangups/client.py", line 209, in _initialize_chat
    data = javascript.loads(data)
  File "/usr/local/lib/python3.4/site-packages/hangups/javascript.py", line 22, in loads
    raise ValueError('Failed to load JavaScript: {}'.format(e))
ValueError: Failed to load JavaScript: Consumed all input without reducing e

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/hangups/javascript.py", line 20, in loads
    return _PARSER.parse(string)
  File "/usr/local/lib/python3.4/site-packages/purplex/parse.py", line 241, in parse
    token = next(tokens)
  File "/usr/local/lib/python3.4/site-packages/purplex/lex.py", line 40, in __iter__
    ret = self.next_token()
  File "/usr/local/lib/python3.4/site-packages/purplex/lex.py", line 81, in next_token
    self.input_text[self.input_pos:self.input_pos + 10],
purplex.exception.NoMatchingTokenFoundError: No token definition matched @ line 216 position 20: '-621435168...'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wazebot/wazebot/hangupsbot/hangupsbot.py", line 164, in run
    loop.run_until_complete(self._client.connect())
  File "/usr/local/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/local/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/usr/local/lib/python3.4/site-packages/hangups/client.py", line 109, in connect
    initial_data = yield from self._initialize_chat()
  File "/usr/local/lib/python3.4/site-packages/hangups/client.py", line 216, in _initialize_chat
    data = javascript.loads(data)
  File "/usr/local/lib/python3.4/site-packages/hangups/javascript.py", line 22, in loads
    raise ValueError('Failed to load JavaScript: {}'.format(e))
ValueError: Failed to load JavaScript: No token definition matched @ line 216 position 20: '-621435168...'
```

**Comment by endofline** [comment]
based on the output, this looks more like a hangups issue. since this appears to be happening using the older version of hangups which we forked off tdryer, i would like to suggest a test migration over to the v3 branch which uses latest hangups if possible. at this point, my older v2 test bot is still running, so i'm unable to repeat these errors

**Comment by JosephBlock** [comment]
I just restarted one of my v2 bots. It shows same error @endofline

**Comment by vaindil** [comment]
Did a hasty merge from the v3.0 branch and all is working now. I'll broadcast to my users to report any issues they find and I'll keep you updated. This issue specifically though is fixed in 3.0, it appears.

**Comment by endofline** [comment]
Google is probably doing a roll-out of changes to the hangouts protocol. V3
uses latest tdryer hangups, so as a reminder to others on the same boat,
you also need to to pip3 install -r requirements.txt again to
install/upgrade your hangups library. If it really is a protocol change,
latest hangups is much more robust in handling it than our old frozen
version of hangups.

V3 branch is currently at beta code quality and should work for most
third-party plugins as long as the plugins were developed following the
V2.4+ standards. If not, YMMV ;p

**Comment by jfx41** [comment]
So, I had the same problem.  Here is what I had to do to fix it (I'm using venvs):

1. git checkout v3.0
2. pip install -r requirements.txt
3. # It fails to install appdirs
4. pip install appdirs --upgrade
5. pip install -r requirements.txt
6. Started the bot

**Comment by endofline** [comment]
managed to repeat this issue, and after a brief moment of flailing around, managed to fix this and get my test v2 bot running again. i'm not being purposefully sarcastic for this comment, the fix amounts to taking random potshots and suddenly having things work again 😕 upgrading to v3 will still be my official recommendation. for those still on v2, you will have to `pip3 install -r requirements.txt --upgrade', basically: rebuild/upgrade your copy of hangups to [0.2.10.2](https://github.com/hangoutsbot/hangups)

**Comment by bafplus** [comment]
I had the same issue today with v2 bot.
I had to do:
pip install appdirs --upgrade
pip install -r requirements.txt

**Comment by Terrance** [comment]
v3 is out and uses the latest upstream hangups, which should solve the issues here.
