### ISSUE TITLE
[v3] Telesync Image sync broken

### ISSUE THREAD

**Issue by phantomdarkness** [hangoutsbot/hangoutsbot#787]
Image sync does not appear to be working.  May not be related to v3, not sure.  Get following errors (seen different ones).  Sometimes works TG->HO but never HO->TG

```
`21:52:30 ERROR handlers: message: plugins.telesync.thunk : coroutine
Traceback (most recent call last):
 File "/home/ubuntu/hangoutsbot/hangupsbot/handlers.py", line 268, in run_pluggable_omnibus
   yield from function(*_passed)
 File "/usr/lib/python3.5/asyncio/coroutines.py", line 209, in coro
   res = yield from res
 File "/home/ubuntu/hangoutsbot/hangupsbot/plugins/telesync/__init__.py", line 868, in _on_hangouts_message
   has_photo, photo_file_name = yield from is_valid_image_link(sync_text)
 File "/home/ubuntu/hangoutsbot/hangupsbot/plugins/telesync/__init__.py", line 843, in is_valid_image_link
   file_ext = content_disp[2].split('.')[1].strip()
IndexError: list index out of range`
```

```
Traceback (most recent call last):
 File "/home/ubuntu/hangoutsbot/hangupsbot/handlers.py", line 268, in run_pluggable_omnibus
   yield from function(*_passed)
 File "/usr/lib/python3.5/asyncio/coroutines.py", line 209, in coro
   res = yield from res
 File "/home/ubuntu/hangoutsbot/hangupsbot/plugins/telesync/__init__.py", line 908, in _on_hangouts_message
   yield from tg_bot.sendPhoto(ho2tg_dict[event.conv_id], open(photo_path, 'rb'))
 File "/home/ubuntu/.local/lib/python3.5/site-packages/telepot/async/__init__.py", line 137, in sendPhoto
   return (yield from self._sendfile(photo, 'photo', p))
 File "/home/ubuntu/.local/lib/python3.5/site-packages/telepot/async/__init__.py", line 126, in _sendfile
   data=data))
 File "/home/ubuntu/.local/lib/python3.5/site-packages/telepot/async/__init__.py", line 37, in _post
   response = yield from aiohttp.post(url, **kwargs)
 File "/home/ubuntu/.local/lib/python3.5/site-packages/aiohttp/client.py", line 629, in __iter__
   return (yield from self._coro)
 File "/home/ubuntu/.local/lib/python3.5/site-packages/aiohttp/client.py", line 220, in _request
   yield from resp.start(conn, read_until_eof)
 File "/home/ubuntu/.local/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 614, in start
   message = yield from httpstream.read()
 File "/home/ubuntu/.local/lib/python3.5/site-packages/aiohttp/streams.py", line 625, in read
   result = yield from super().read()
 File "/home/ubuntu/.local/lib/python3.5/site-packages/aiohttp/streams.py", line 456, in read
   yield from self._waiter
 File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
   yield self  # This tells Task to wait for completion.
 File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
   future.result()
 File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
   raise self._exception
aiohttp.errors.ClientRequestError: Can not write request body for https://api.telegram.org/bot303611931:AAEFaFQ_CFBbXRWMyJgDbDeVKy7jpYvcMOk/sendPhoto
```

**Comment by phantomdarkness** [comment]
Also get a lot of this on pluginload

```
`Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/telepot/async/__init__.py", line 343, in get_from_telegram_server
    result = yield from self.getUpdates(offset=offset, timeout=20)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/telepot/async/__init__.py", line 266, in getUpdates
    data=_rectify(p)))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/telepot/async/__init__.py", line 59, in _post
    raise TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Not Found', 404, {'ok': False, 'description': 'Not Found', 'error_code': 404})`
```

**Comment by phantomdarkness** [comment]
Probably unrelated, but noticed that images are being saved to a new directory /hangupsbot/plugins/telesync as opposed to main directory of /hangoutsbot/hangupsbot/plugins/telesync.

Adding "hangoutsbot/" to lines 312, 351, and 890

**Comment by pleasantone** [comment]
Yeah, that's fundamentally broken.
Do you need them saved at all? In my rewrite I've moved them to temp files that get unlinked.

We should not be writing to the code directory.

**Comment by phantomdarkness** [comment]
No, don't need them saved, just noticing if they are going to be saved, not being saved correctly under code.

**Comment by pleasantone** [comment]
Whew, good. Yeah it's my intention to remove the save functionality

**Comment by phantomdarkness** [comment]
Is your rewrite functional at all? happy to beta test :-)

**Comment by pleasantone** [comment]
Not ready to ship

**Comment by JosephBlock** [comment]
Should images instead be using the systems temp folder using tempfile module?

**Comment by pleasantone** [comment]
Yeah, the new code uses pythons tempfile stuff and wipes them away when done.
