### ISSUE TITLE
telesync problem with messages containing "<"

### ISSUE THREAD

**Issue by Astrofreak85** [hangoutsbot/hangoutsbot#788]
If someone writes a message in Hangouts containing "<" it is not forwarded to telegram.

Log: 

```
2017-03-14 13:09:47 INFO event: len/tx: 4/<>
?
2017-03-14 13:09:47 ERROR handlers: message: plugins.telesync.thunk : coroutine
Traceback (most recent call last):
 File "/home/resdd/bot/hangoutsbot/hangupsbot/handlers.py", line 259, in run_pluggable_omnibus
   yield from function(*_passed)
 File "/usr/lib/python3.4/asyncio/coroutines.py", line 143, in coro
   res = yield from res
 File "/home/resdd/bot/hangoutsbot/hangupsbot/plugins/telesync/__init__.py", line 887, in _on_hangouts_message
   disable_web_page_preview=True)
 File "/home/resdd/env/hangoutsbot/lib/python3.4/site-packages/telepot/async/__init__.py", line 90, in sendMessage
   data=_rectify(p)))
 File "/home/resdd/env/hangoutsbot/lib/python3.4/site-packages/telepot/async/__init__.py", line 59, in _post
   raise TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Request: can\'t parse message text: Unsupported start tag "" at byte offset 79', 400, {'ok': False, 'description': 'Bad Request: can\'t parse message text: Unsupported start tag "" at byte offset 79', 'error_code': 400})
```

**Comment by Terrance** [comment]
This seems to be working as of v3.
