### ISSUE TITLE
[v3] IndexError: list index out of range

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#790]
Upon first boot of a bot, I get this error

```
09:50:12 ERROR root: CLIENT: unrecoverable low-level error
Traceback (most recent call last):
  File "/usr/local/share/hangoutsbot/hangupsbot/hangupsbot.py", line 164, in run
    loop.run_until_complete(self._client.connect())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/share/hangoutsbot/venv/lib/python3.5/site-packages/hangups/client.py", line 122, in connect
    yield from self._listen_future
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/share/hangoutsbot/venv/lib/python3.5/site-packages/hangups/channel.py", line 209, in listen
    yield from self._longpoll_request()
  File "/usr/local/share/hangoutsbot/venv/lib/python3.5/site-packages/hangups/channel.py", line 338, in _longpoll_request
    yield from self._on_push_data(chunk)
  File "/usr/local/share/hangoutsbot/venv/lib/python3.5/site-packages/hangups/channel.py", line 359, in _on_push_data
    yield from self.on_connect.fire()
  File "/usr/local/share/hangoutsbot/venv/lib/python3.5/site-packages/hangups/event.py", line 60, in fire
    yield from gen
  File "/usr/local/share/hangoutsbot/venv/lib/python3.5/site-packages/hangups/event.py", line 60, in fire
    yield from gen
  File "/usr/local/share/hangoutsbot/hangupsbot/hangupsbot.py", line 547, in _on_connect
    yield from hangups.build_user_conversation_list(self._client)
  File "/usr/local/share/hangoutsbot/venv/lib/python3.5/site-packages/hangups/conversation.py", line 57, in build_user_conversation_list
    conv_event = conv_state.event[0]
  File "/usr/local/share/hangoutsbot/venv/lib/python3.5/site-packages/google/protobuf/internal/containers.py", line 204, in __getitem__
    return self._values[key]
IndexError: list index out of range
Client unexpectedly disconnected:
list index out of range
```

Other bots running on the same code work fine, I have tried logging into the account using lynx and I can log in via the server fine. This bot account has worked in the past on v2.

**Comment by endofline** [comment]
#751

**Comment by nylonee** [comment]
Whoops. Missed that. Can we leave this open for a bit longer so that others who have the same error don't re-create a new issue?

**Comment by Terrance** [comment]
Think we're good to close this now.
