### ISSUE TITLE
[v3] [chatbridge/telesync] Coroutine errors preventing sync from working

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#793]
I've got a few errors happening on the [chatbridge/telesync](https://github.com/hangoutsbot/hangoutsbot/tree/chatbridge/telesync) branch, listing them below:

Error 1: KeyError on config
```
2017-03-16 23:56:14 ERROR asyncio: Task exception was never retrieved
future: <Task finished coro=<TelegramBot.handle() done, defined at /usr/local/share/hangoutsbot/hangupsbot/plugins/telesync/__init__.py:138> exception=KeyError('be_quiet',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/share/hangoutsbot/hangupsbot/plugins/telesync/__init__.py", line 157, in handle
    if self.config['be_quiet']:
KeyError: 'be_quiet'
```

Error 2: TypeError on every message sent from a hangout (images included)
```
2017-03-16 23:56:36 ERROR handlers: message: plugins.telesync.thunk : coroutine
Traceback (most recent call last):
  File "/usr/local/share/hangoutsbot/hangupsbot/handlers.py", line 293, in run_pluggable_omnibus
    yield from function(*_passed)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 209, in coro
    res = yield from res
  File "/usr/local/share/hangoutsbot/hangupsbot/plugins/telesync/__init__.py", line 887, in _on_hangouts_message
    disable_web_page_preview=True)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
```

Error 3: Images not being received from telegram. See #787

**Comment by nylonee** [comment]
@endofline Take note
