### ISSUE TITLE
[v3] Images do not sync from Slack to TG across chatbridge

### ISSUE THREAD

**Issue by phantomdarkness** [hangoutsbot/hangoutsbot#823]
Get the following error when sending from Slack to TG.  Image show up in HO.  Image syncs fine from TG->HO->Slack, it's just Slack->HO->TG

```
2017-04-09 12:38:52 WARNING plugins.slackrtm.core: could not find channel "G4M52V52N" although --

-8<---8<--- snip ---8<---8<---

2017-04-09 12:38:54 INFO event: len/tx: 174/phantomdarkness (MATH): shared media from slack
https://lh3.googleusercontent.com/-W8_7YpEGxVI/WOpjnRbWEWI/AAAAAAAACh0/hGPcqYgcFoo9XhMsDCFZBeOjGHVTS2F0QCK8B/s0/2015-07-19.jpg

---8<---8<--- snip ---8<---8<---

2017-04-09 12:38:56 ERROR asyncio: Task exception was never retrieved
future: <Task finished coro=<EventHandler.image_uri_from() done, defined at /home/ubuntu/hangoutsbot/hangupsbot/handlers.py:128> exception=TelegramError('Bad Request: failed to get HTTP URL content', 400, {'error_code': 400, 'ok': False, 'description': 'Bad Request: failed to get HTTP URL content'})>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/ubuntu/hangoutsbot/hangupsbot/handlers.py", line 142, in image_uri_from
    yield from callback(self._image_ids[image_id], *args, **kwargs)
  File "/home/ubuntu/hangoutsbot/hangupsbot/plugins/telesync/__init__.py", line 963, in _send_deferred_media
    media_link )
  File "/home/ubuntu/.local/lib/python3.5/site-packages/telepot/aio/__init__.py", line 120, in sendPhoto
    return await self._sendfile(photo, 'photo', p)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/telepot/aio/__init__.py", line 98, in _sendfile
    return await self._api_request(method, _rectify(params))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/telepot/aio/__init__.py", line 70, in _api_request
    return await api.request((self._token, method, params, files), **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/telepot/aio/api.py", line 111, in request
    return await _parse(r)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/telepot/aio/api.py", line 100, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Request: failed to get HTTP URL content', 400, {'error_code': 400, 'ok': False, 'description': 'Bad Request: failed to get HTTP URL content'})
```

@endofline edited: used code blocks, shortened log to highlight specifics

**Comment by Aspersat** [comment]
Got something similar here:
Only syncing HO<->TG

TG->HO does not sync image
HO->TG syncs image OK

Log while loading image to TG
`2017-04-09 23:43:55 INFO plugins.telesync: unmapped/invalid hangouts user for 200541874
2017-04-09 23:43:55 INFO plugins.telesync: no hangups user for 200541874
2017-04-09 23:43:55 INFO webbridge: telegramTelesync:receive:{'original_request': {'image_id': None, 'user': 'Grillo', 'segments': None, 'message': '_uploading photo from Grillo in #Paris Highrollers_'}, 'chatbridge': {'source_title': '#Paris Highrollers', 'source_uid': 200541874, 'plugin': 'telegramTelesync', 'source_gid': 'telegramTelesync', 'source_user': 'Grillo'}, 'norelay': ['telegramTelesync-0']}
2017-04-09 23:43:55 DEBUG handlers: sending: plugins.telesync._broadcast : coroutine
2017-04-09 23:43:55 INFO webbridge: telegramTelesync:telegramTelesync-0:NORELAY:broadcast:['telegramTelesync-0']
2017-04-09 23:43:55 DEBUG root: message sending: global context = {'passthru': {'original_request': {'image_id': None, 'user': 'Grillo', 'segments': None, 'message': '_uploading photo from Grillo in #Paris Highrollers_'}, 'chatbridge': {'source_title': '#Paris Highrollers', 'source_uid': 200541874, 'plugin': 'telegramTelesync', 'source_gid': 'telegramTelesync', 'source_user': 'Grillo'}, 'norelay': ['telegramTelesync-0']}, 'base': {'tags': ['legacy'], 'source': 'unknown', 'importance': 50}}
2017-04-09 23:43:55 DEBUG root: message sending: UgzpcnTsY8Q2WS89OmR4AaABAQ
2017-04-09 23:43:56 INFO event: eid/dt: 8GBeX6p2TYA8R91eRGuIBH/2017-04-09 23:43:56
2017-04-09 23:43:56 INFO event: cid/cn: UgzpcnTsY8Q2WS89OmR4AaABAQ/#Paris Highrollers V.5
2017-04-09 23:43:56 INFO event: c/g/un: 113929755078456779648/113929755078456779648/chsync
2017-04-09 23:43:56 INFO event: len/tx: 67/Grillo: uploading photo from Grillo in #Paris Highrollers
2017-04-09 23:43:56 DEBUG handlers: allmessages: plugins.telesync._repeat : coroutine
2017-04-09 23:43:56 INFO webbridge: telegramTelesync:telegramTelesync-0:NORELAY:repeat:['telegramTelesync-0']
2017-04-09 23:43:56 INFO plugins.telesync: retrieving: photos/file_196.jpg
2017-04-09 23:43:56 WARNING plugins.telesync: no shared hangoutsbot image upload, please add image plugin to your list of plugins
2017-04-09 23:43:56 INFO plugins.telesync: no hangups user for 200541874
2017-04-09 23:43:56 INFO webbridge: telegramTelesync:receive:{'original_request': {'image_id': False, 'user': 'Grillo', 'segments': None, 'message': 'sent a photo, but telesync could not load it'}, 'chatbridge': {'source_title': '#Paris Highrollers', 'source_uid': 200541874, 'plugin': 'telegramTelesync', 'source_gid': 'telegramTelesync', 'source_user': 'Grillo'}, 'norelay': ['telegramTelesync-0']}
2017-04-09 23:43:56 DEBUG handlers: sending: plugins.telesync._broadcast : coroutine
2017-04-09 23:43:56 INFO webbridge: telegramTelesync:telegramTelesync-0:NORELAY:broadcast:['telegramTelesync-0']
2017-04-09 23:43:56 DEBUG root: message sending: global context = {'passthru': {'original_request': {'image_id': False, 'user': 'Grillo', 'segments': None, 'message': 'sent a photo, but telesync could not load it'}, 'chatbridge': {'source_title': '#Paris Highrollers', 'source_uid': 200541874, 'plugin': 'telegramTelesync', 'source_gid': 'telegramTelesync', 'source_user': 'Grillo'}, 'norelay': ['telegramTelesync-0']}, 'base': {'tags': ['legacy'], 'source': 'unknown', 'importance': 50}}
2017-04-09 23:43:56 DEBUG root: message sending: UgzpcnTsY8Q2WS89OmR4AaABAQ
2017-04-09 23:43:56 INFO plugins.telesync: photo posted to hangouts
2017-04-09 23:43:57 INFO event: eid/dt: 8GBeX6p2TYA8R91eVhDP9k/2017-04-09 23:43:56
2017-04-09 23:43:57 INFO event: cid/cn: UgzpcnTsY8Q2WS89OmR4AaABAQ/#Paris Highrollers V.5
2017-04-09 23:43:57 INFO event: c/g/un: 113929755078456779648/113929755078456779648/chsync
2017-04-09 23:43:57 INFO event: len/tx: 57/Grillo: sent a photo, but telesync could not load it
2017-04-09 23:43:57 DEBUG handlers: allmessages: plugins.telesync._repeat : coroutine
2017-04-09 23:43:57 INFO webbridge: telegramTelesync:telegramTelesync-0:NORELAY:repeat:['telegramTelesync-0']`

**Comment by endofline** [comment]
prior to continuing on this issue, i would like to point out that [code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) are a thing ;p

**Comment by endofline** [comment]
@aspersat - as per the upgrade guidance in #761 and the [telesync plugin](https://github.com/hangoutsbot/hangoutsbot/wiki/telesync-Plugin) - please add the `image` plugin - this problem is unrelated with the issue being reported by @phantomdarkness

**Comment by endofline** [comment]
@phantomdarkness - i cannot repeat this bug for image sending. some observations:
* i used the same image you did - as the link shown in the log is publicly available - advise caution if you are accidentally sharing privileged information
* my configuration is 2 slack channels (works in both) -> HO -> telegram 
* the exception indicates that the error is from telegram servers, not telesync, so it could be a transient error
  * to elaborate: `Bad Request: failed to get HTTP URL content` is an error from telegram servers attempting to access the public image link on google
* the only novel thing about your log is an error on slackrtm i haven't seen before, which i highlighted in the (edited) log you posted - it didn't affect the image posting though, as evidenced in the second line, the image is retrieved and sent correctly to HO

**Comment by phantomdarkness** [comment]
Yep, synced this time.  Weird.  Thanks!
