### ISSUE TITLE
Create 1:1 -- Abuse service requested this end user operation to be rejected

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#828]
```
2017-04-09 16:07:08 INFO root: get_1on1: remembered XXX for NNN
2017-04-09 16:07:08 INFO plugins.mentions: @mention 'pepper' in 'QQQ' (ZZZ)
2017-04-09 16:07:08 INFO plugins.mentions: user XXX (NNN) is present
2017-04-09 16:07:08 INFO root: get_1on1: creating 1to1 with NNN
2017-04-09 16:07:08 ERROR root: GET_1TO1: failed to create 1-to-1 for user 112360431497521326769
Traceback (most recent call last):
  File "/home/pst/hangoutsbot/hangupsbot/hangupsbot.py", line 471, in get_1to1
    response = yield from self._client.create_conversation(request)
  File "/srv/hangoutsbot/lib/python3.5/site-packages/hangups/client.py", line 441, in create_conversation
    create_conversation_request, response)
  File "/srv/hangoutsbot/lib/python3.5/site-packages/hangups/client.py", line 379, in _pb_request
    .format(status, description)
hangups.exceptions.NetworkError: Request failed with status 4: 'Abuse service requested this end-user operation to be rejected'
2017-04-09 16:07:10 WARNING plugins.mentions: user XXX (NNN) could not be alerted via 1on1
```

I wonder what's triggering google to think my bot is a spambot?

**Comment by endofline** [comment]
inviting further comments from botmins, perhaps there is a combination of internal and external factors causing this issue? the implementation of the [actual protobuf request](https://github.com/hangoutsbot/hangoutsbot/blob/v3.0/hangupsbot/hangupsbot.py#L465) looks like its by the book

**Comment by nylonee** [comment]
Out of curiosity, have you set up a recovery email/phone number on the account that's causing the issues? Not sure if that influences how likely your bot is to be flagged...

**Comment by pleasantone** [comment]
They both exist, and no problems.

**Comment by OllieTerrance** [comment]
If it's reproducible, maybe worth trying it manually, using the bot account on [hangouts.google.com](https://hangouts.google.com)?  Could give you a more public-facing error message, more likely to come up in search results...

**Comment by pleasantone** [comment]
I cannot reproduce it.
