### ISSUE TITLE
[v3] duplicate slack/hangouts messages (double-echo)

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#858]
## Description
Hangouts and SlackRTM bridged
## Output of `/bot version`
v3.0 branch as of the past month
## Expected behaviour
normal behavior
## Actual behaviour
we see everything that is generated in hangouts come through twice on slack
## Steps to reproduce:
  1. Set it up and wait
  2. Randomly, days later, this happens
  3. ...
## Log output
```
2017-05-24 21:06:03 INFO webbridge: slackRTM:slackRTM-5:NORELAY:broadcast:['slackRTM-5']
2017-05-24 21:06:04 INFO webbridge: slackRTM:slackRTM-5:NORELAY:repeat:['slackRTM-5']
2017-05-24 21:20:40 INFO root: Connection lost!
2017-05-24 21:20:43 ERROR asyncio: Unclosed connection
client_connection: Connection<('0.client-channel.google.com', 443, True)>
2017-05-24 21:21:26 ERROR plugins.slackrtm.core: WebSocketConnectionClosedException(Connection is already closed.)
Traceback (most recent call last):
  File "/home/pst/hangoutsbot/hangupsbot/plugins/slackrtm/core.py", line 980, in run
    replies = self._listener.rtm_read()
  File "/home/pst/hangoutsbot/hangupsbot/plugins/slackrtm/core.py", line 495, in rtm_read
    return self.slack.rtm_read()
  File "/srv/hangoutsbot/lib/python3.5/site-packages/slackclient/_client.py", line 123, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/srv/hangoutsbot/lib/python3.5/site-packages/slackclient/_server.py", line 141, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_core.py", line 293, in recv
    opcode, data = self.recv_data()
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_core.py", line 310, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_core.py", line 323, in recv_data_frame
    frame = self.recv_frame()
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_core.py", line 357, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_abnf.py", line 336, in recv_frame
    self.recv_header()
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_abnf.py", line 286, in recv_header
    header = self.recv_strict(2)
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_abnf.py", line 371, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_core.py", line 427, in _recv
    return recv(self.sock, bufsize)
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_socket.py", line 93, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
2017-05-24 21:21:27 INFO plugins.slackrtm.core: started RTM connection for SlackRTM thread <SlackRTMThread(SlackRTM:sfr, started daemon 140003283928832)>
2017-05-24 21:21:27 INFO root: list_conversations: 523 from permamem, 516 from hangups - discrepancies: none
2017-05-24 21:27:26 ERROR plugins.slackrtm.core: WebSocketConnectionClosedException(Connection is already closed.)
Traceback (most recent call last):
  File "/home/pst/hangoutsbot/hangupsbot/plugins/slackrtm/core.py", line 980, in run
    replies = self._listener.rtm_read()
  File "/home/pst/hangoutsbot/hangupsbot/plugins/slackrtm/core.py", line 495, in rtm_read
    return self.slack.rtm_read()
  File "/srv/hangoutsbot/lib/python3.5/site-packages/slackclient/_client.py", line 123, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/srv/hangoutsbot/lib/python3.5/site-packages/slackclient/_server.py", line 141, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_core.py", line 293, in recv
    opcode, data = self.recv_data()
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_core.py", line 310, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_core.py", line 323, in recv_data_frame
    frame = self.recv_frame()
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_core.py", line 357, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_abnf.py", line 336, in recv_frame
    self.recv_header()
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_abnf.py", line 286, in recv_header
    header = self.recv_strict(2)
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_abnf.py", line 371, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_core.py", line 427, in _recv
    return recv(self.sock, bufsize)
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_socket.py", line 93, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
2017-05-24 21:27:26 INFO plugins.slackrtm.core: started RTM connection for SlackRTM thread <SlackRTMThread(SlackRTM:ebres, started daemon 140003273438976)>
2017-05-24 21:27:26 INFO root: list_conversations: 523 from permamem, 516 from hangups - discrepancies: none



2017-05-25 07:16:31 INFO root: Connection lost!
2017-05-25 07:16:34 ERROR asyncio: Unclosed connection
client_connection: Connection<('0.client-channel.google.com', 443, True)>
2017-05-25 08:11:22 INFO webbridge: slackRTM:slackRTM-5:repeat:['slackRTM-5']
2017-05-25 08:11:22 INFO webbridge: hangouts user raised an event, first seen by slackRTM
2017-05-25 08:11:22 INFO plugins.slackrtm.bridgeinstance: slackRTM:slackRTM-5:_send_to_external_chat, slackrtms = 2
2017-05-25 08:11:22 INFO plugins.slackrtm.core: message C09B7LNDD: Had a great time in town for Navarro. Thanks all! <ho://UgwJQjlOfzJaEFBCYlN4AaABAQ/107285872164587677096| >
2017-05-25 08:11:22 INFO webbridge: slackRTM:slackRTM-11:repeat:['slackRTM-5', 'slackRTM-11']
2017-05-25 08:11:22 INFO plugins.slackrtm.bridgeinstance: slackRTM:slackRTM-11:_send_to_external_chat, slackrtms = 2
2017-05-25 08:11:22 INFO plugins.slackrtm.core: message C09B7LNDD: Had a great time in town for Navarro. Thanks all! <ho://UgwJQjlOfzJaEFBCYlN4AaABAQ/107285872164587677096| >
2017-05-25 08:11:29 INFO permamem: conv participants changed The City by the Bay Visitors Guide: http://sfbay.resists.org/sfc/visitors . (UgwJQjlOfzJaEFBCYlN4AaABAQ)
2017-05-25 08:11:29 INFO permamem: conv UgwJQjlOfzJaEFBCYlN4AaABAQ updated The City by the Bay Visitors Guide: http://sfbay.resists.org/sfc/visitors .
2017-05-25 08:11:30 INFO config: /home/discobot/.local/share/hangupsbot/memory.json write 0.12978553771972656
2017-05-25 08:14:42 INFO permamem: conv participants changed The City by the Bay Visitors Guide: http://sfbay.resists.org/sfc/visitors . (UgwJQjlOfzJaEFBCYlN4AaABAQ)
2017-05-25 08:14:42 INFO permamem: conv UgwJQjlOfzJaEFBCYlN4AaABAQ updated The City by the Bay Visitors Guide: http://sfbay.resists.org/sfc/visitors .
2017-05-25 08:14:43 INFO config: /home/discobot/.local/share/hangupsbot/memory.json write 0.1319131851196289
2017-05-25 08:24:41 INFO root: Connection lost!
2017-05-25 16:04:26 INFO plugins.slackrtm.bridgeinstance: no hangups user for sfr U0CLXD3AP
2017-05-25 16:04:26 INFO webbridge: slackRTM:receive:{'norelay': ['slackRTM-6'], 'original_request': {'image_id': None, 'segments': None, 'message': 'If anyone needs keys from xxxxxxxxxxxx, ping me direct.', 'user': 'Tim Pozar (timitheo)'}, 'chatbridge': {'source_title': 'sf-fidi-hangout', 'source_edited': None, 'source_user': 'Tim Pozar (timitheo)', 'source_action': None, 'source_gid': 'C094TGHL0', 'source_uid': 'U0CLXD3AP', 'plugin': 'slackRTM'}}
2017-05-25 16:04:26 INFO webbridge: slackRTM:slackRTM-0:broadcast:['slackRTM-6', 'slackRTM-0']
2017-05-25 16:04:26 INFO plugins.slackrtm.bridgeinstance: slackRTM:slackRTM-0:_send_to_external_chat, slackrtms = 2
2017-05-25 16:04:26 INFO plugins.slackrtm.core: message C094TGHL0: If anyone needs keys from xxxxxxxxxxxx, ping me direct. <ho://UgyS8TvClcBbYeFUBmF4AaABAQ/Tim Pozar (timitheo)| >
2017-05-25 16:04:26 INFO webbridge: slackRTM:slackRTM-6:NORELAY:broadcast:['slackRTM-6', 'slackRTM-0']
2017-05-25 16:04:27 INFO webbridge: slackRTM:slackRTM-0:NORELAY:repeat:['slackRTM-6', 'slackRTM-0']
2017-05-25 16:04:27 INFO webbridge: slackRTM:slackRTM-6:NORELAY:repeat:['slackRTM-6', 'slackRTM-0']
2017-05-25 16:07:14 INFO plugins.slackrtm.bridgeinstance: no hangups user for sfr U099J9R5E
2017-05-25 16:07:14 INFO webbridge: slackRTM:receive:{'norelay': ['slackRTM-6'], 'original_request': {'image_id': None, 'segments': None, 'message': 'Lead a BAF @timitheo :)', 'user': 'Alex Z (c0mradeX)'}, 'chatbridge': {'source_title': 'sf-fidi-hangout', 'source_edited': None, 'source_user': 'Alex Z (c0mradeX)', 'source_action': None, 'source_gid': 'C094TGHL0', 'source_uid': 'U099J9R5E', 'plugin': 'slackRTM'}}
2017-05-25 16:07:14 INFO webbridge: slackRTM:slackRTM-0:broadcast:['slackRTM-6', 'slackRTM-0']
2017-05-25 16:07:14 INFO plugins.slackrtm.bridgeinstance: slackRTM:slackRTM-0:_send_to_external_chat, slackrtms = 2
2017-05-25 16:07:14 INFO plugins.slackrtm.core: message C094TGHL0: Lead a BAF @timitheo :) <ho://UgyS8TvClcBbYeFUBmF4AaABAQ/Alex Z (c0mradeX)| >
2017-05-25 16:07:14 INFO webbridge: slackRTM:slackRTM-6:NORELAY:broadcast:['slackRTM-6', 'slackRTM-0']
2017-05-25 16:07:15 INFO webbridge: slackRTM:slackRTM-0:NORELAY:repeat:['slackRTM-6', 'slackRTM-0']
2017-05-25 16:07:15 INFO webbridge: slackRTM:slackRTM-6:NORELAY:repeat:['slackRTM-6', 'slackRTM-0']
2017-05-25 16:10:46 INFO plugins.slackrtm.bridgeinstance: no hangups user for sfr U02NXCSR6
2017-05-25 16:10:46 INFO webbridge: slackRTM:receive:{'norelay': ['slackRTM-6'], 'original_request': {'image_id': None, 'segments': None, 'message': 'echo', 'user': 'Nick Parker (NickyP)'}, 'chatbridge': {'source_title': 'sf-fidi-hangout', 'source_edited': None, 'source_user': 'Nick Parker (NickyP)', 'source_action': None, 'source_gid': 'C094TGHL0', 'source_uid': 'U02NXCSR6', 'plugin': 'slackRTM'}}
2017-05-25 16:10:46 INFO webbridge: slackRTM:slackRTM-0:broadcast:['slackRTM-6', 'slackRTM-0']
2017-05-25 16:10:46 INFO plugins.slackrtm.bridgeinstance: slackRTM:slackRTM-0:_send_to_external_chat, slackrtms = 2
2017-05-25 16:10:46 INFO plugins.slackrtm.core: message C094TGHL0: echo <ho://UgyS8TvClcBbYeFUBmF4AaABAQ/Nick Parker (NickyP)| >
2017-05-25 16:10:46 INFO webbridge: slackRTM:slackRTM-6:NORELAY:broadcast:['slackRTM-6', 'slackRTM-0']
2017-05-25 16:10:47 INFO webbridge: slackRTM:slackRTM-0:NORELAY:repeat:['slackRTM-6', 'slackRTM-0']
2017-05-25 16:10:47 INFO webbridge: slackRTM:slackRTM-6:NORELAY:repeat:['slackRTM-6', 'slackRTM-0']
2017-05-25 16:16:21 INFO plugins.slackrtm.bridgeinstance: no hangups user for sfr U099J9R5E
2017-05-25 16:16:21 INFO webbridge: slackRTM:receive:{'norelay': ['slackRTM-6'], 'original_request': {'image_id': None, 'segments': None, 'message': 'Bravo ', 'user': 'Alex Z (c0mradeX)'}, 'chatbridge': {'source_title': 'sf-fidi-hangout', 'source_edited': None, 'source_user': 'Alex Z (c0mradeX)', 'source_action': None, 'source_gid': 'C094TGHL0', 'source_uid': 'U099J9R5E', 'plugin': 'slackRTM'}}
2017-05-25 16:16:21 INFO webbridge: slackRTM:slackRTM-0:broadcast:['slackRTM-6', 'slackRTM-0']
2017-05-25 16:16:21 INFO plugins.slackrtm.bridgeinstance: slackRTM:slackRTM-0:_send_to_external_chat, slackrtms = 2
2017-05-25 16:16:21 INFO plugins.slackrtm.core: message C094TGHL0: Bravo  <ho://UgyS8TvClcBbYeFUBmF4AaABAQ/Alex Z (c0mradeX)| >
2017-05-25 16:16:21 INFO webbridge: slackRTM:slackRTM-6:NORELAY:broadcast:['slackRTM-6', 'slackRTM-0']
2017-05-25 16:16:22 INFO webbridge: slackRTM:slackRTM-0:NORELAY:repeat:['slackRTM-6', 'slackRTM-0']
2017-05-25 16:16:22 INFO webbridge: slackRTM:slackRTM-6:NORELAY:repeat:['slackRTM-6', 'slackRTM-0']
```

**Comment by pleasantone** [comment]
I suspect it happened because of the two connection losts the previous hours before...

**Comment by OllieTerrance** [comment]
I can reproduce this too.  The first log line here looks like one of the spurious disconnect messages as noted in #852.

```
08:54:30 WARNING plugins.slackrtm.core: no type available for {}
08:54:30 ERROR plugins.slackrtm.core: WebSocketConnectionClosedException(Connection is already closed.)
Traceback (most recent call last):
  File "hangupsbot/plugins/slackrtm/core.py", line 1019, in run
    replies = self._listener.rtm_read()
  File "hangupsbot/plugins/slackrtm/core.py", line 519, in rtm_read
    return self.slack.rtm_read()
  ...
  File "venv/lib/python3.6/site-packages/websocket/_socket.py", line 93, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
08:54:30 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): slack.com
08:54:31 INFO plugins.slackrtm.core: started RTM connection for SlackRTM thread <SlackRTMThread(SlackRTM:..., started daemon 140147668547328)>
08:54:31 INFO root: list_conversations: 158 from permamem, 147 from hangups - discrepancies: none
10:20:23 INFO event: eid/dt: .../2017-05-27 10:19:28
10:20:23 INFO event: cid/cn: .../...
10:20:23 INFO event: c/g/un: .../.../...
10:20:23 INFO event: len/tx: .../...
10:20:23 INFO webbridge: slackRTM:slackRTM-0:repeat:['slackRTM-0']
10:20:23 INFO webbridge: hangouts user raised an event, first seen by slackRTM
10:20:23 INFO plugins.slackrtm.bridgeinstance: slackRTM:slackRTM-0:_send_to_external_chat, slackrtms = 1
10:20:23 INFO plugins.slackrtm.core: message ...: ... <ho://.../...| >
10:20:23 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): slack.com
10:20:24 INFO webbridge: slackRTM:slackRTM-5:repeat:['slackRTM-0', 'slackRTM-5']
10:20:24 INFO plugins.slackrtm.bridgeinstance: slackRTM:slackRTM-5:_send_to_external_chat, slackrtms = 1
10:20:24 INFO plugins.slackrtm.core: message ...: ... <ho://.../...| >
```

**Comment by OllieTerrance** [comment]
#859 is likely the same issue.

**Comment by phantomdarkness** [comment]
Yes happening to me too

**Comment by azack** [comment]
not occurring at older commit 5315e5d5f00005b076e717cb6e06d59b0bb5987d with bot in hangout<->slack<->hangout config

**Comment by pleasantone** [comment]
Again:

```
2017-05-30 23:13:56 INFO plugins.slackrtm.bridgeinstance: no hangups user for sfr U02G6HKN4
2017-05-30 23:13:56 INFO webbridge: slackRTM:receive:{'original_request': {'message': 'k np', 'user': 'Dennis C (dorkus)', 'segments': None, 'image_id': None}, 'chatbridge': {'source_user': 'Dennis C (dorkus)', 'source_uid': 'U02G6HKN4', 'source_edited': None, 'source_gid': 'C09B7LNDD', 'source_action': None, 'source_title': 'sf-visitors-hangout', 'plugin': 'slackRTM'}, 'norelay': ['slackRTM-5']}
2017-05-30 23:13:56 INFO webbridge: slackRTM:slackRTM-5:NORELAY:broadcast:['slackRTM-5']
2017-05-30 23:13:56 INFO webbridge: slackRTM:slackRTM-5:NORELAY:repeat:['slackRTM-5']
2017-05-30 23:26:50 INFO root: Connection lost!
2017-05-30 23:27:01 ERROR asyncio: Unclosed connection
client_connection: Connection<('0.client-channel.google.com', 443, True)>
2017-05-31 00:02:28 INFO root: Connection lost!
2017-05-31 00:02:44 ERROR asyncio: Unclosed connection
client_connection: Connection<('0.client-channel.google.com', 443, True)>
2017-05-31 03:11:40 WARNING plugins.slackrtm.core: no type available for {}
2017-05-31 03:11:40 ERROR plugins.slackrtm.core: WebSocketConnectionClosedException(Connection is already closed.)
Traceback (most recent call last):
  File "/home/pst/hangoutsbot/hangupsbot/plugins/slackrtm/core.py", line 980, in run
    replies = self._listener.rtm_read()
  File "/home/pst/hangoutsbot/hangupsbot/plugins/slackrtm/core.py", line 495, in rtm_read
    return self.slack.rtm_read()
  File "/srv/hangoutsbot/lib/python3.5/site-packages/slackclient/_client.py", line 123, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/srv/hangoutsbot/lib/python3.5/site-packages/slackclient/_server.py", line 141, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_core.py", line 293, in recv
    opcode, data = self.recv_data()
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_core.py", line 310, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_core.py", line 323, in recv_data_frame
    frame = self.recv_frame()
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_core.py", line 357, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_abnf.py", line 336, in recv_frame
    self.recv_header()
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_abnf.py", line 286, in recv_header
    header = self.recv_strict(2)
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_abnf.py", line 371, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_core.py", line 427, in _recv
    return recv(self.sock, bufsize)
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_socket.py", line 93, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
2017-05-31 03:11:41 INFO plugins.slackrtm.core: started RTM connection for SlackRTM thread <SlackRTMThread(SlackRTM:sfr, started daemon 140199807784704)>
2017-05-31 03:11:41 INFO root: list_conversations: 527 from permamem, 520 from hangups - discrepancies: none
2017-05-31 03:12:12 WARNING plugins.slackrtm.core: no type available for {}
2017-05-31 03:12:12 ERROR plugins.slackrtm.core: WebSocketConnectionClosedException(Connection is already closed.)
Traceback (most recent call last):
  File "/home/pst/hangoutsbot/hangupsbot/plugins/slackrtm/core.py", line 980, in run
    replies = self._listener.rtm_read()
  File "/home/pst/hangoutsbot/hangupsbot/plugins/slackrtm/core.py", line 495, in rtm_read
    return self.slack.rtm_read()
  File "/srv/hangoutsbot/lib/python3.5/site-packages/slackclient/_client.py", line 123, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/srv/hangoutsbot/lib/python3.5/site-packages/slackclient/_server.py", line 141, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_core.py", line 293, in recv
    opcode, data = self.recv_data()
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_core.py", line 310, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_core.py", line 323, in recv_data_frame
    frame = self.recv_frame()
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_core.py", line 357, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_abnf.py", line 336, in recv_frame
    self.recv_header()
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_abnf.py", line 286, in recv_header
    header = self.recv_strict(2)
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_abnf.py", line 371, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_core.py", line 427, in _recv
    return recv(self.sock, bufsize)
  File "/srv/hangoutsbot/lib/python3.5/site-packages/websocket/_socket.py", line 93, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
2017-05-31 03:12:13 INFO plugins.slackrtm.core: started RTM connection for SlackRTM thread <SlackRTMThread(SlackRTM:ebres, started daemon 140199797294848)>
2017-05-31 03:12:13 INFO root: list_conversations: 527 from permamem, 520 from hangups - discrepancies: none
2017-05-31 06:29:44 INFO root: Connection lost!
2017-05-31 06:29:47 ERROR asyncio: Unclosed connection
client_connection: Connection<('0.client-channel.google.com', 443, True)>
2017-05-31 09:19:27 INFO plugins.slackrtm.bridgeinstance: no hangups user for sfr U02NXCSR6
2017-05-31 09:19:27 INFO webbridge: slackRTM:receive:{'original_request': {'message': '[redacted1]', 'user': 'Nick Parker (NickyP)', 'segments': None, 'image_id': None}, 'chatbridge': {'source_user': 'Nick Parker (NickyP)', 'source_uid': 'U02NXCSR6', 'source_edited': None, 'source_gid': 'C094TGHL0', 'source_action': None, 'source_title': 'sf-fidi-hangout', 'plugin': 'slackRTM'}, 'norelay': ['slackRTM-6']}
2017-05-31 09:19:27 INFO webbridge: slackRTM:slackRTM-0:broadcast:['slackRTM-6', 'slackRTM-0']
2017-05-31 09:19:27 INFO plugins.slackrtm.bridgeinstance: slackRTM:slackRTM-0:_send_to_external_chat, slackrtms = 2
2017-05-31 09:19:27 INFO plugins.slackrtm.core: message C094TGHL0: [redacted1] <ho://UgyS8TvClcBbYeFUBmF4AaABAQ/Nick Parker (NickyP)| >
2017-05-31 09:19:27 INFO webbridge: slackRTM:slackRTM-6:NORELAY:broadcast:['slackRTM-6', 'slackRTM-0']
2017-05-31 09:19:28 INFO webbridge: slackRTM:slackRTM-0:NORELAY:repeat:['slackRTM-6', 'slackRTM-0']
2017-05-31 09:19:28 INFO webbridge: slackRTM:slackRTM-6:NORELAY:repeat:['slackRTM-6', 'slackRTM-0']
2017-05-31 09:28:00 INFO webbridge: slackRTM:slackRTM-0:repeat:['slackRTM-0']
2017-05-31 09:28:00 INFO webbridge: hangouts user raised an event, first seen by slackRTM
2017-05-31 09:28:00 INFO plugins.slackrtm.bridgeinstance: slackRTM:slackRTM-0:_send_to_external_chat, slackrtms = 2
2017-05-31 09:28:00 INFO plugins.slackrtm.core: message C094TGHL0: [redacted2] <ho://UgyS8TvClcBbYeFUBmF4AaABAQ/106564787726997609302| >
2017-05-31 09:28:00 INFO webbridge: slackRTM:slackRTM-6:repeat:['slackRTM-0', 'slackRTM-6']
2017-05-31 09:28:00 INFO plugins.slackrtm.bridgeinstance: slackRTM:slackRTM-6:_send_to_external_chat, slackrtms = 2
2017-05-31 09:28:00 INFO plugins.slackrtm.core: message C094TGHL0: [redacted2] <ho://UgyS8TvClcBbYeFUBmF4AaABAQ/106564787726997609302| >
2017-05-31 09:28:26 INFO webbridge: slackRTM:slackRTM-0:repeat:['slackRTM-0']
2017-05-31 09:28:26 INFO webbridge: hangouts user raised an event, first seen by slackRTM
2017-05-31 09:28:26 INFO plugins.slackrtm.bridgeinstance: slackRTM:slackRTM-0:_send_to_external_chat, slackrtms = 2
2017-05-31 09:28:26 INFO plugins.slackrtm.core: message C094TGHL0: [redacted3]  ☺ <ho://UgyS8TvClcBbYeFUBmF4AaABAQ/106564787726997609302| >
2017-05-31 09:28:27 INFO webbridge: slackRTM:slackRTM-6:repeat:['slackRTM-0', 'slackRTM-6']
2017-05-31 09:28:27 INFO plugins.slackrtm.bridgeinstance: slackRTM:slackRTM-6:_send_to_external_chat, slackrtms = 2
2017-05-31 09:28:27 INFO plugins.slackrtm.core: message C094TGHL0: [redacted3]  ☺ <ho://UgyS8TvClcBbYeFUBmF4AaABAQ/106564787726997609302| >
2017-05-31 09:46:11 INFO plugins.slackrtm.bridgeinstance: no hangups user for sfr U02QSUSSA
2017-05-31 09:46:11 INFO webbridge: slackRTM:receive:{'original_request': {'message': 'anyone who annoys Daila is a dear dear friend 💙 😻', 'user': 'Benson (wolfhorn)', 'segments': None, 'image_id': None}, 'chatbridge': {'source_user': 'Benson (wolfhorn)', 'source_uid': 'U02QSUSSA', 'source_edited': None, 'source_gid': 'C094TGHL0', 'source_action': None, 'source_title': 'sf-fidi-hangout', 'plugin': 'slackRTM'}, 'norelay': ['slackRTM-6']}
2017-05-31 09:46:11 INFO webbridge: slackRTM:slackRTM-0:broadcast:['slackRTM-6', 'slackRTM-0']
2017-05-31 09:46:11 INFO plugins.slackrtm.bridgeinstance: slackRTM:slackRTM-0:_send_to_external_chat, slackrtms = 2
2017-05-31 09:46:11 INFO plugins.slackrtm.core: message C094TGHL0: [redacted4]
 <ho://UgyS8TvClcBbYeFUBmF4AaABAQ/Benson (wolfhorn)| >
2017-05-31 09:46:11 INFO webbridge: slackRTM:slackRTM-6:NORELAY:broadcast:['slackRTM-6', 'slackRTM-0']
2017-05-31 09:46:12 INFO webbridge: slackRTM:slackRTM-0:NORELAY:repeat:['slackRTM-6', 'slackRTM-0']
2017-05-31 09:46:12 INFO webbridge: slackRTM:slackRTM-6:NORELAY:repeat:['slackRTM-6', 'slackRTM-0']
2017-05-31 10:09:40 INFO plugins.slackrtm.bridgeinstance: no hangups user for sfr U02QPCYLW
2017-05-31 10:09:40 INFO webbridge: slackRTM:receive:{'original_request': {'message': "[redacted5]", 'user': 'k0re777', 'segments': None, 'image_id': None}, 'chatbridge': {'source_user': 'k0re777', 'source_uid': 'U02QPCYLW', 'source_edited': None, 'source_gid': 'C094TGHL0', 'source_action': None, 'source_title': 'sf-fidi-hangout', 'plugin': 'slackRTM'}, 'norelay': ['slackRTM-6']}
2017-05-31 10:09:40 INFO webbridge: slackRTM:slackRTM-0:broadcast:['slackRTM-6', 'slackRTM-0']
2017-05-31 10:09:40 INFO plugins.slackrtm.bridgeinstance: slackRTM:slackRTM-0:_send_to_external_chat, slackrtms = 2
```

**Comment by pleasantone** [comment]
@azack it may be the case that it doesn't occur there (5315e5d) , but that's definitely not the cluprit

**Comment by azack** [comment]
@pleasantone Yup. just mentioning if someone wanted to revert or bisect.

**Comment by OllieTerrance** [comment]
All the except clauses [restart the thread method](https://github.com/hangoutsbot/hangoutsbot/blob/v3.0/hangupsbot/plugins/slackrtm/core.py#L1004-L1018).  This recreates the listener without stopping the current one, causing the duplication.

**Comment by pleasantone** [comment]
SlackRTMThread.run at https://github.com/hangoutsbot/hangoutsbot/blob/v3.0/hangupsbot/plugins/slackrtm/core.py#L971 removes the listener from the list.

SlackRTM.__init__ at https://github.com/hangoutsbot/hangoutsbot/blob/v3.0/hangupsbot/plugins/slackrtm/core.py#L293 looks like it wants to reap the old thread, but I think that's not occurring because we're not creating a new thread, we're recycling the old thread -- so there are TWO listeners on a single thread?  But then why are we getting new names? (SlackRTM-0 vs SlackRTM-5)

**Comment by azack** [comment]
I think this can be closed.
