### ISSUE TITLE
ImportError: No module named '_overlapped'

### ISSUE THREAD

**Issue by PlayerEugene** [hangoutsbot/hangoutsbot#862]
When trying to run hangoutsbot for the first time, I get an error saying

```
$ python3 hangupsbot/hangupsbot.py -d
Traceback (most recent call last):
  File "C:\Python34\lib\asyncio\__init__.py", line 16, in <module>
    from . import _overlapped
ImportError: cannot import name '_overlapped'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hangupsbot/hangupsbot.py", line 2, in <module>
    import appdirs, argparse, asyncio, gettext, logging, logging.config, os, shutil, signal, sys, time
  File "C:\Python34\lib\asyncio\__init__.py", line 18, in <module>
    import _overlapped  # Will also be exported.
ImportError: No module named '_overlapped'
```

How can I fix this?

**Comment by OllieTerrance** [comment]
Have you installed asyncio yourself?  You should only need to do that on Python 3.3.

The [install docs for asyncio](https://pypi.python.org/pypi/asyncio) do mention an extra step for `_unwrapped` on Windows, it's under Development though so not sure if that applies normally.
