### ISSUE TITLE
[v3] Images failing to sync with slack to multi hangouts

### ISSUE THREAD

**Issue by azack** [hangoutsbot/hangoutsbot#863]
## Description

Images are (sometimes?) failing to send from slack to hangout "B" with slackrtm under v3 with a slack channel set to sync to hangouts A and B.

## Output of `/bot version`

```
Bot Version: 3.0.0-beta
Python Version: 3.5.1
* aiohttp 2.1.0
* appdirs 1.4.3
* emoji 0.4.5
* hangups 0.4.2
* telepot 12.0
```

## Expected behaviour

Images should sync as expected.

## Actual behaviour

The image to hangout A works as expected, but when sending to hangout B we get no image sent.  Similarly sometimes the image goes to B ok, but fails to send to A.

## Steps to reproduce:
  1. Configure a slack channel to sync to two hangouts
  2. Send an image from the slack channel

## Log output

```
2017-06-09 20:08:05 INFO event: eid/dt: 7-H0Z7-6yZg8TawAkj2dhl/2017-06-09 20:08:04
2017-06-09 20:08:05 INFO event: cid/cn: <hangout a id>/<hangout a name>
2017-06-09 20:08:05 INFO event: c/g/un: <bot id>/<bot id>/<bot name>
2017-06-09 20:08:05 INFO event: len/tx: 190/<slack user id>: shared media from slack
<https url to image>.png
2017-06-09 20:08:05 INFO handlers: associating image_id=6429732989765616066 with <https url to image>.png
2017-06-09 20:08:05 INFO handlers: current event is executable: shared media from slack
2017-06-09 20:08:05 INFO webbridge: slackRTM:slackRTM-28:NORELAY:repeat:['slackRTM-28']
2017-06-09 20:08:11 ERROR root: CORO_SEND_MESSAGE: error sending <hangout b id>
Traceback (most recent call last):
  File "/home/hangupsbot/hangupsbot/hangupsbot/hangupsbot.py", line 761, in coro_send_message
    context = context )
  File "/home/hangupsbot/hangupsbot-official/hangupsbot/hangups_conversation.py", line 252, in send_message
    expected_otr = otr_status )))
  File "/usr/local/lib/python3.5/site-packages/hangups/client.py", line 568, in send_chat_message
    send_chat_message_request, response)
  File "/usr/local/lib/python3.5/site-packages/hangups/client.py", line 395, in _pb_request
    .format(status, description)
hangups.exceptions.NetworkError: Request failed with status 3: 'Unexpected error'
``````

**Comment by OllieTerrance** [comment]
Is it only specific to images via Slack?

Can you get around it by using `Slack <-slackrtm-> HO <-syncrooms-> HO`?

**Comment by Terrance** [comment]
The above is the expected way of dealing with Slack + 2x Hangouts.  v3 chatbridge should hopefully improve the handling of messages across multiple bridges.
