### ISSUE TITLE
[v3] Slack sync sometimes crashes bot

### ISSUE THREAD

**Issue by vaindil** [hangoutsbot/hangoutsbot#875]
## Description
Receiving an error that causes the bot to stop working entirely. The process continues running, but the bot no longer syncs to Slack or Discord and does not respond to any commands. Nothing is written to the log after the exception.

## Output of `/bot version`
Bot Version: **3.0.0-beta**
Python Version: **3.6.1**
* aiohttp **2.2.3**
* appdirs **1.4.3**
* emoji **0.4.5**
* hangups **0.4.2**
* telepot **12.1**

## Expected behaviour
Nothing should crash

## Actual behaviour
It crashes ;)

## Log output
Note: The exception block appears twice, but it's exactly the same so I only pasted it below once.
```
2017-07-25 16:39:42 INFO plugins.slackrtm.core: started RTM connection for SlackRTM thread <SlackRTMThread(SlackRTM:wazesm, started daemon 140419024889600)>
2017-07-25 16:39:42 INFO plugins.slackrtm.core: old thread found: <SlackRTMThread(SlackRTM:wazesm, started daemon 140419146708736)> - killing it
16:39:42 INFO plugins.slackrtm.core: started RTM connection for SlackRTM thread <SlackRTMThread(SlackRTM:wazesm, started daemon 140419024889600)>
16:39:42 INFO plugins.slackrtm.core: old thread found: <SlackRTMThread(SlackRTM:wazesm, started daemon 140419146708736)> - killing it
2017-07-25 16:39:42 ERROR plugins.slackrtm.core: SlackRTMThread: unhandled exception: ['sending'] handler(s) <bound method WebFramework._broadcast of <plugins.slackrtm.bridgeinstance.BridgeInstance object at 0x7fb5e21a5128>>
Traceback (most recent call last):
  File "/home/wazebot/wazebot/hangupsbot/plugins/slackrtm/core.py", line 980, in run
    self._listener = SlackRTM(self._config, self._bot, self._loop, threaded=True)
  File "/home/wazebot/wazebot/hangupsbot/plugins/slackrtm/core.py", line 295, in __init__
    t.stop()
  File "/home/wazebot/wazebot/hangupsbot/plugins/slackrtm/core.py", line 1032, in stop
    self._listener.close()
  File "/home/wazebot/wazebot/hangupsbot/plugins/slackrtm/core.py", line 958, in close
    s._bridgeinstance.close()
  File "/home/wazebot/wazebot/hangupsbot/webbridge/__init__.py", line 65, in close
    plugins.deregister_handler(self._handler_broadcast, type="sending")
  File "/home/wazebot/wazebot/hangupsbot/plugins/__init__.py", line 220, in deregister_handler
    bot_handlers.deregister_handler(function, type)
  File "/home/wazebot/wazebot/hangupsbot/handlers.py", line 128, in deregister_handler
    raise ValueError("{} handler(s) {}".format(type, function))
ValueError: ['sending'] handler(s) <bound method WebFramework._broadcast of <plugins.slackrtm.bridgeinstance.BridgeInstance object at 0x7fb5e21a5128>>
```

**Comment by OllieTerrance** [comment]
Possibly a side-effect of #860, there may be more to it when registering handlers ad-hoc.  🤔

Looks like we're not matching the original function we registered at load time.

**Comment by das7pad** [comment]
As soon as the started `SlackRTMThread` stops, the full bot halts. I can confirm this as well.

**Comment by Terrance** [comment]
The SlackRTM rewrite `_chatbridge.chatbridge_slackrtm` does the deregistration differently and should hopefully not have this trouble.
