### ISSUE TITLE
Upgrade from 2.7.10 to 2.8 get slackrtm module error

### ISSUE THREAD

**Issue by ppescitelli** [hangoutsbot/hangoutsbot#892]
## Output of `/bot version` . 2.8
23:42:17 INFO plugins: mentions - bemorespecific, *mention, pushbulletapi, setnickname
23:42:17 INFO plugins: subscribe - subscribe, *testsubscribe, unsubscribe
23:42:17 INFO plugins: autoreply - *autoreply
23:42:17 INFO plugins: dnd - dnd
23:42:17 INFO plugins: starter - *files, iamspartacus, *test_one2one_message, verifyme
23:42:17 INFO plugins.botaliases: aliases: ['/bot', '/atlres', '/108057666152611094775', '!', 'help']
23:42:17 INFO plugins: botaliases - botalias
23:42:17 ERROR plugins: EXCEPTION during plugin import: plugins.slackrtm
Traceback (most recent call last):
  File "/home/paul_pescitelli/hangoutsbot/hangupsbot/plugins/__init__.py", line 345, in load
    importlib.import_module(module_path)
  File "/usr/local/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/paul_pescitelli/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 65, in <module>
    emoji.EMOJI_UNICODE[':simple_smile:'] = emoji.EMOJI_UNICODE[':white_smiling_face:']
KeyError: ':white_smiling_face:'
23:42:17 INFO plugins: remind - remindall, remindme
23:42:17 INFO root: bot initialised

**Comment by jbonnier** [comment]
I had that problem too with slackrtm, temporarily fixed the problem commenting line 65 and 66 of hangoutsbot/hangupsbot/plugins/slackrtm.py.

**Comment by OllieTerrance** [comment]
Wrong version of the `emoji` library?  The failing line there is a monkeypatch to cover Slack's non-standard `simple_smile` emoji, though `white_smiling_face` was removed in a later library version.

**Comment by ppescitelli** [comment]
what is the command to pull the v3 branch for slackRTM from command line?

**Comment by ppescitelli** [comment]
figured it out...

git stash
git checkout v3.0
git pull

**Comment by ppescitelli** [comment]
after doing the above command, now have another issue

paul_pescitelli@hobot ~]$ sudo /usr/local/bin/python3.4 /home/paul_pescitelli/hangoutsbot/hangupsbot/hangupsbot.py
 -d --config ~/.local/share/hangupsbot/config.json
Traceback (most recent call last):
  File "/home/paul_pescitelli/hangoutsbot/hangupsbot/hangupsbot.py", line 6, in <module>
    import hangups_shim
  File "/home/paul_pescitelli/hangoutsbot/hangupsbot/hangups_shim.py", line 1, in <module>
    from hangups import hangouts_pb2
ImportError: cannot import name 'hangouts_pb2'

**Comment by OllieTerrance** [comment]
You're probably still using hangoutsbot's outdated fork of hangups, did you install the requirements?

```pip install --upgrade -r requirements.txt```
