### ISSUE TITLE
Telesync - No synchronization of images with Smartfone upload

### ISSUE THREAD

**Issue by Blaphase** [hangoutsbot/hangoutsbot#894]
I have a hangupsbot standart installation (Bot Version: 2.8.0) with Telesync running on a Ubuntu 16.10 minimum server. The synchronization of text messages between Hangouts and Telegram works as expected. Synchronizing images uploaded from the PC also works, but images sent from the Smartfone are not synchronized. Both from HO to TG and vice versa. 
It does not matter whether the configuration is set, whether the images are to be saved or not. There are no further error messages in the log.

For me, it looks like an array isn't being properly initialized:

```
09:07:23 ERROR handlers: message: plugins.telesync.thunk : coroutine
Traceback (most recent call last):
  File "/home/r2d2/hangoutsbot-master/hangupsbot/handlers.py", line 263, in run_pluggable_omnibus yield from function(*_passed)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 209, in corores = yield from res
  File "/home/r2d2/hangoutsbot-master/hangupsbot/plugins/telesync/__init__.py", line 870, in_on_hangouts_message
09:07:23 ERROR handlers: message: plugins.telesync.thunk : coroutine
Traceback (most recent call last):
  File "/home/r2d2/hangoutsbot-master/hangupsbot/handlers.py", line 263, in run_pluggable_omnibus yield from function(*_passed)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 209, in corores = yield from res
  File "/home/r2d2/hangoutsbot-master/hangupsbot/plugins/telesync/__init__.py", line 870, in _on_hangouts_message
    has_photo, photo_file_name = yield from is_valid_image_link(sync_text)
  File "/home/r2d2/hangoutsbot-master/hangupsbot/plugins/telesync/__init__.py", line 841, in is_valid_image_link
    file_ext = content_disp[2].split('.')[1].strip()
IndexError: list index out of range
```
Any idea what to do with that error?

Kind regards
Bla

**Comment by das7pad** [comment]
v2.8 and v3.0 expect a full filename in the content-disposition of the remote resource. This is not always the case. See this example `'inline;filename="0123456789"'` (_the actual number was different_).
Let's take a look at the handling:
https://github.com/hangoutsbot/hangoutsbot/blob/master/hangupsbot/plugins/telesync/__init__.py#L839..L841

line | result
 -- | --
839 | `content_disp = 'inline;filename="0123456789"'`
840 | `content_disp = ['inline;filename', '0123456789']`
841 | `IndexError: list index out of range` as there are just 2 items

A possible fix for line 841 is `file_ext = content_disp[-1].split('.')[-1].strip()`, but this does not cover filenames that do not contain an extension.

_A solution to deal with missing file-extensions can be found [here](https://github.com/das7pad/hangoutsbot/blob/dev/hangupsbot/sync/image.py#L307..L319)._
