### ISSUE TITLE
SlackRTM : slack_syncto command fails

### ISSUE THREAD

**Issue by jbonnier** [hangoutsbot/hangoutsbot#895]
## Description
Whenever I run a slack_syncto command I get an error message.
## Output of `/bot version`
Bot Version: 3.0.0-beta
Python Version: 3.4.2
* aiohttp 2.3.2
* appdirs 1.4.3
* emoji 0.4.5
* hangups 0.4.3
* telepot 12.4
## Expected behaviour
OK, I will now sync all messages in this Hangout to slack_team:slack_channel
## Actual behaviour
slack_syncto AttributeError: 'method' object has no attribute '_is_coroutine'
## Steps to reproduce:
  1. Clone the repository
  2. Checkout to branch v3.0
  3. Install the requirements with pip
  4. Run the bot
  5. Identify as admin with iamspartacus
  6. Enable plugin SlackRTM
  7. SlackRTM configs to config file
  8. /bot slack_syncto slack_team channel_id
## Log output

```
09:38:49 INFO event: len/tx: 35//bot slack_syncto slack_team XXXXXXXX
09:38:49 ERROR commands: RUN: slack_syncto
Traceback (most recent call last):
  File "/home/hobot/hangoutsbot/hangupsbot/commands/__init__.py", line 436, in run
    results = yield from func(bot, event, *args, **kwds)
  File "/home/hobot/hangoutsbot/hangupsbot/plugins/slackrtm/commands_hangouts.py", line 199, in slack_syncto
    slackrtm.config_syncto(channelid, event.conv.id_, honame)
  File "/home/hobot/hangoutsbot/hangupsbot/plugins/slackrtm/core.py", line 566, in config_syncto
    sync = SlackRTMSync(self.bot, channel, hangoutid, shortname, self.get_teamname())
  File "/home/hobot/hangoutsbot/hangupsbot/plugins/slackrtm/core.py", line 212, in __init__
    self._bridgeinstance = BridgeInstance(hangoutsbot, "slackrtm", extra_metadata = handler_metadata)
  File "/home/hobot/hangoutsbot/hangupsbot/webbridge/__init__.py", line 60, in __init__
    self._handler_repeat = plugins.register_handler(self._repeat, type="allmessages", extra_metadata=extra_metadata)
  File "/home/hobot/hangoutsbot/hangupsbot/plugins/__init__.py", line 215, in register_handler
    return bot_handlers.register_handler(function, type, priority, extra_metadata=extra_metadata)
  File "/home/hobot/hangoutsbot/hangupsbot/handlers.py", line 66, in register_handler
    _handler = asyncio.coroutine(_handler)
  File "/usr/lib/python3.4/asyncio/coroutines.py", line 160, in coroutine
    wrapper._is_coroutine = True  # For iscoroutinefunction().
AttributeError: 'method' object has no attribute '_is_coroutine'
09:38:49 ERROR handlers: sending: plugins.slackrtm._broadcast : coroutine
Traceback (most recent call last):
  File "/home/hobot/hangoutsbot/hangupsbot/commands/__init__.py", line 436, in run
    results = yield from func(bot, event, *args, **kwds)
  File "/home/hobot/hangoutsbot/hangupsbot/plugins/slackrtm/commands_hangouts.py", line 199, in slack_syncto
    slackrtm.config_syncto(channelid, event.conv.id_, honame)
  File "/home/hobot/hangoutsbot/hangupsbot/plugins/slackrtm/core.py", line 566, in config_syncto
    sync = SlackRTMSync(self.bot, channel, hangoutid, shortname, self.get_teamname())
  File "/home/hobot/hangoutsbot/hangupsbot/plugins/slackrtm/core.py", line 212, in __init__
    self._bridgeinstance = BridgeInstance(hangoutsbot, "slackrtm", extra_metadata = handler_metadata)
  File "/home/hobot/hangoutsbot/hangupsbot/webbridge/__init__.py", line 60, in __init__
    self._handler_repeat = plugins.register_handler(self._repeat, type="allmessages", extra_metadata=extra_metadata)
  File "/home/hobot/hangoutsbot/hangupsbot/plugins/__init__.py", line 215, in register_handler
    return bot_handlers.register_handler(function, type, priority, extra_metadata=extra_metadata)
  File "/home/hobot/hangoutsbot/hangupsbot/handlers.py", line 66, in register_handler
    _handler = asyncio.coroutine(_handler)
  File "/usr/lib/python3.4/asyncio/coroutines.py", line 160, in coroutine
    wrapper._is_coroutine = True  # For iscoroutinefunction().
AttributeError: 'method' object has no attribute '_is_coroutine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hobot/hangoutsbot/hangupsbot/handlers.py", line 412, in run_pluggable_omnibus
    yield from function(*_passed)
  File "/home/hobot/hangoutsbot/hangupsbot/webbridge/__init__.py", line 108, in _broadcast
    applicable_configurations = self.applicable_configuration(conv_id)
  File "/home/hobot/hangoutsbot/hangupsbot/plugins/slackrtm/bridgeinstance.py", line 30, in applicable_configuration
    if conv_id != self.hangouts_id:
AttributeError: 'BridgeInstance' object has no attribute 'hangouts_id'
09:38:50 INFO event: eid/dt: XXXXXXXXXXXXXXXXX/2017-11-13 09:38:56
09:38:50 INFO event: cid/cn: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/Me
09:38:50 INFO event: c/g/un: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/Bot User
09:38:50 INFO event: len/tx: 77/slack_syncto AttributeError: 'method' object has no attribute '_is_coroutine'

```

**Comment by das7pad** [comment]
Python 3.4.2 is fairly old (_release date 2014-10-13_), could you try to run the bot with a Python version greater 3.5?

**Comment by jbonnier** [comment]
Thanks das7pad.

Using python 3.5 problem is gone!

**Comment by Terrance** [comment]
3.4.4 is now the minimum Python version supported, which included asyncio fixes that may have covered the `_is_coroutine` error here.
