### ISSUE TITLE
Can't initialize chat, KeyError: 'ds:7"

### ISSUE THREAD

**Issue by robklob** [hangoutsbot/hangoutsbot#932]
This started happening about a week ago. Not sure why. Have completely reinstalled to the latest version of this bot and Python/PIP. Not sure what this error indicates . . . . was hoping someone could point me in the right direction.

Thanks!

C:\hangoutsbot>python3 hangupsbot/hangupsbot.py
'python3' is not recognized as an internal or external command,
operable program or batch file.

C:\hangoutsbot>python hangupsbot/hangupsbot.py
20:45:02 INFO config: C:\Users\Owner\AppData\Local\hangupsbot\hangupsbot\config.json read
20:45:02 INFO root: memory = C:\Users\Owner\AppData\Local\hangupsbot\hangupsbot\memory.json, failsafe = 3, delay = 1
20:45:02 INFO root: creating memory file: C:\Users\Owner\AppData\Local\hangupsbot\hangupsbot\memory.json
20:45:02 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): accounts.google.com
Sign in with your Google account:
Email: 20:45:03 INFO config: C:\Users\Owner\AppData\Local\hangupsbot\hangupsbot\memory.json write 0.0
EMAILADDRESS@gmail.com
Password:
**20:46:20 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.google.com
**20:46:22 ERROR root: CLIENT: unrecoverable low-level error
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\hangups\client.py", line 227, in _initialize_chat
    self._api_key = data_dict['ds:7'][0][2]
KeyError: 'ds:7'****

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hangupsbot/hangupsbot.py", line 164, in run
    loop.run_until_complete(self._client.connect())
  File "C:\Python36\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "C:\Python36\lib\site-packages\hangups\client.py", line 109, in connect
    initial_data = yield from self._initialize_chat()
  File "C:\Python36\lib\site-packages\hangups\client.py", line 241, in _initialize_chat
    'value: {}'.format(e))
hangups.exceptions.HangupsError: Failed to get initialize chat value: 'ds:7'
Client unexpectedly disconnected:
Failed to get initialize chat value: 'ds:7'
20:46:22 INFO root: Waiting 5 seconds...
20:46:27 INFO root: Trying to connect again (try 1 of 5)...
20:46:32 ERROR root: CLIENT: unrecoverable low-level error
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\hangups\client.py", line 227, in _initialize_chat
    self._api_key = data_dict['ds:7'][0][2]
KeyError: 'ds:7'

**Comment by JosephBlock** [comment]
Upgrade to v3 or use https://github.com/hangoutsbot/hangoutsbot/issues/925 temporary fix

**Comment by robklob** [comment]
Awesome - thanks so much will try that out . . .

**Comment by robklob** [comment]
Thanks, JosephBlock. That did the trick!
