### ISSUE TITLE
Bot Alias requires call to help before working

### ISSUE THREAD

**Issue by Warfields** [hangoutsbot/hangoutsbot#937]
## Description
The bot will not accept an alias until the alias is call with help.
## Output of `/bot version`
Bot Version: 3.0.0-beta
Python Version: 3.5.3
* aiohttp 2.3.10
* appdirs 1.4.3
* emoji 0.5.0
* hangups 0.4.5
* telepot 12.7
## Expected behaviour
/bot botalias pie
pie ping
pong
## Actual behaviour
/bot botalias pie
pie ping
## Steps to reproduce:
  1. "/bot botalias pie"
  2. "pie ping"
  3. Nothing appears on hangouts and an exception is raised but does not crash the bot
## Log output

```
17:09:34 ERROR asyncio: Exception in callback HangupsBot._on_event.<locals>.<lambda>(<Task finishe...ot defined",)>) at hangupsbot/hangupsbot.py:617
handle: <Handle HangupsBot._on_event.<locals>.<lambda>(<Task finishe...ot defined",)>) at hangupsbot/hangupsbot.py:617>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "hangupsbot/hangupsbot.py", line 617, in <lambda>
    ).add_done_callback(lambda future: future.result())
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/pi/hangoutsbot/hangupsbot/handlers.py", line 292, in handle_chat_message
    yield from self.handle_command(event)
  File "/home/pi/hangoutsbot/hangupsbot/handlers.py", line 332, in handle_command
    config_silent = bot.get_config_suboption(event.conv.id_, 'silentmode')
NameError: name 'bot' is not defined

```

**Comment by OllieTerrance** [comment]
Looks like that `bot` should be `self.bot` instead.
