### ISSUE TITLE
Suddenly "LOGIN FAILED"

### ISSUE THREAD

**Issue by PonasKovas** [hangoutsbot/hangoutsbot#950]
## Description
So basically I have been running this bot for about a year now, and today when I ran it, it suddenly crashed, saying that it can't login.
## Version
I'm using v3.0
## Log output

```
03:22:16 INFO config: ./edible/config.json read
03:22:16 ERROR root: no translation for en
Traceback (most recent call last):
  File "hangupsbot.py", line 334, in set_locale
    self._locales[language_code] = gettext.translation('hangupsbot', localedir=os.path.join(os.path.dirname(__file__), 'locale'), languages=[language_code])
  File "/app/.heroku/python/lib/python3.6/gettext.py", line 514, in translation
    raise OSError(ENOENT, 'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'hangupsbot'
03:22:16 WARNING root: LOCALE: en
03:22:16 INFO root: memory = ./edible/memory.json, failsafe = 3, delay = 1
03:22:16 INFO config: ./edible/memory.json read
03:22:17 ERROR root: LOGIN FAILED
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/hangups/auth.py", line 373, in _get_session_cookies
    r.raise_for_status()
  File "/app/.heroku/python/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://www.google.com/sorry/index?continue=https://www.google.com/&q=EgQ2TqJOGOnr0N0FIhkA8aeDS8HvqYCsxzGDewun95LO_FidT9p4MgFy

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hangupsbot.py", line 372, in login
    cookies = hangups.auth.get_auth_stdin(cookies_path)
  File "/app/.heroku/python/lib/python3.6/site-packages/hangups/auth.py", line 186, in get_auth_stdin
    return get_auth(CredentialsPrompt(), refresh_token_cache)
  File "/app/.heroku/python/lib/python3.6/site-packages/hangups/auth.py", line 172, in get_auth
    return _get_session_cookies(session, access_token)
  File "/app/.heroku/python/lib/python3.6/site-packages/hangups/auth.py", line 375, in _get_session_cookies
    raise GoogleAuthError('MergeSession request failed: {}'.format(e))
hangups.auth.GoogleAuthError: MergeSession request failed: 503 Server Error: Service Unavailable for url: https://www.google.com/sorry/index?continue=https://www.google.com/&q=EgQ2TqJOGOnr0N0FIhkA8aeDS8HvqYCsxzGDewun95LO_FidT9p4MgFy
03:22:17 ERROR root: Valid login required, exiting
```
I haven't changed anything since yesterday and the login credentials are correct. What could be the problem?

**Comment by PonasKovas** [comment]
Yeah so I tried launching it again and now it works.

**Comment by PonasKovas** [comment]
@OllieTerrance how can I make sure this doesn't happen again?

**Comment by OllieTerrance** [comment]
Not much you can do, Google's explanation of "unusual traffic" is deliberately vague.  It usually happens when attempting to sign in from a new IP address, or if you sign in a few times in quick succession, but there may be other causes.
