### ISSUE TITLE
Api cert file error

### ISSUE THREAD

**Issue by GodschildGaming** [hangoutsbot/hangoutsbot#952]
## Description
The cert file when pluged in won't load even after fallowing the steps of how to make a self certified cert
## Output of `/bot version
3.0.0-Beta`
## Expected behaviour
to start and listen on port
## Actual behaviour
gives a SSL error when trying to start api port listen
## Log output

```
17:16:25 ERROR plugins: EXCEPTION during plugin init: plugins.api
Traceback (most recent call last):
  File "C:\a\plugins\__init__.py", line 434, in load
    the_function(bot)
  File "C:\a\plugins\api.py", line 32, in _initialise
    _start_api(bot)
  File "C:\a\plugins\api.py", line 76, in _start_api
    aiohttp_start(bot, name, port, certfile, APIRequestHandler, group=__name__)
  File "C:\a\sinks\__init__.py", line 152, in aiohttp_start
    sslcontext.load_cert_chain(certfile)
ssl.SSLError: [SSL] PEM lib (_ssl.c:3358)
```

**Comment by GodschildGaming** [comment]
Ok so me being me decided to do even more research then I could understand and figured a way to edit the sinks code it self to work for my needs so what I did was simple instead of supplying just the cert file like the sinks file wanted I recoded it to want both the key file and cert file and now it works perfectly.
