### ISSUE TITLE
Manual login option?

### ISSUE THREAD

**Issue by stephenuwu** [hangoutsbot/hangoutsbot#966]
## Description
On my first run of the bot, I got thrown with an error listed below in Log output. This was the exact same error that happened when I ran `hangups` in cygwin. When I ran `hangups --manual-login`, it seemed to work and allowed me to run `hangups` without any issues.

I'm using python 3.8 from the cygwin package.
Is there a way I can ran hangupsbot and provide the token manually? Thanks for your time.

## Log output

```
16:22:41 ERROR root: LOGIN FAILED
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/hangups/auth.py", line 198, in get_auth
    raise GoogleAuthError("Refresh token not found")
hangups.auth.GoogleAuthError: Refresh token not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/hangups/auth.py", line 272, in submit_form
    form = self._page.soup.select(form_selector)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hangupsbot/hangupsbot.py", line 139, in login
    cookies = hangups.auth.get_auth_stdin(cookies_path)
  File "/usr/local/lib/python3.8/site-packages/hangups/auth.py", line 233, in get_auth_stdin
    return get_auth(
  File "/usr/local/lib/python3.8/site-packages/hangups/auth.py", line 208, in get_auth
    authorization_code = _get_authorization_code(
  File "/usr/local/lib/python3.8/site-packages/hangups/auth.py", line 321, in _get_authorization_code
    browser.submit_form(FORM_SELECTOR, {PASSWORD_SELECTOR: password})
  File "/usr/local/lib/python3.8/site-packages/hangups/auth.py", line 274, in submit_form
    raise GoogleAuthError(
hangups.auth.GoogleAuthError: Failed to find form '#gaia_loginform' in page
16:22:41 ERROR root: Valid login required, exiting

```

**Comment by Terrance** [comment]
The token from hangups can be found at `~/.cache/hangups/refresh_token.txt`, copy it to `~/.local/share/hangoutsbot/cookies.json` for hangoutsbot to use it.

**Comment by stephenuwu** [comment]
> 
> 
> The token from hangups can be found at `~/.cache/hangups/refresh_token.txt`, copy it to `~/.local/share/hangoutsbot/cookies.json` for hangoutsbot to use it.

I only see 3 files,
config.json, hangupsbot.log, memory.json.
I assume I'm supposed to make a new json file or edit one of the existing ones? Thanks for your time btw.

**Comment by Terrance** [comment]
`cookies.json` is where you're copying it to, it won't exist if you haven't logged in with hangoutsbot yet.

**Comment by YeemBoi** [comment]
You can login manually by changing 
`cookies = hangups.auth.get_auth_stdin(cookies_path)` to
`cookies = hangups.auth.get_auth_stdin(cookies_path, manual_login=True)`
on line 139 of `hangupsbot/hangupsbot.py`. It's a quick and dirty fix, but got the job done for me when I had this issue.

**Comment by stephenuwu** [comment]
> 
> 
> You can login manually by changing
> `cookies = hangups.auth.get_auth_stdin(cookies_path)` to
> `cookies = hangups.auth.get_auth_stdin(cookies_path, manual_login=True)`
> on line 139 of `hangupsbot/hangupsbot.py`. It's a quick and dirty fix, but got the job done for me when I had this issue.

That seemed to work for me, thanks!

**Comment by ghost** [comment]
I did manual login, but I'm now getting this error:
```
16:33:46 ERROR root: LOGIN FAILED
Traceback (most recent call last):
  File "C:\Users\bekfe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\hangups\auth.py", line 198, in get_auth
    raise GoogleAuthError("Refresh token not found")
hangups.auth.GoogleAuthError: Refresh token not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bekfe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\hangups\auth.py", line 392, in _make_token_request
    r.raise_for_status()
  File "C:\Users\bekfe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://accounts.google.com/o/oauth2/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bekfe\OneDrive\Desktop\google-chat-bot\hangoutsbot\hangupsbot\hangupsbot.py", line 139, in login
    cookies = hangups.auth.get_auth_stdin(cookies_path, manual_login=True)
  File "C:\Users\bekfe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\hangups\auth.py", line 233, in get_auth_stdin
    return get_auth(
  File "C:\Users\bekfe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\hangups\auth.py", line 211, in get_auth
    access_token, refresh_token = _auth_with_code(
  File "C:\Users\bekfe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\hangups\auth.py", line 379, in _auth_with_code
    res = _make_token_request(session, token_request_data)
  File "C:\Users\bekfe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\hangups\auth.py", line 394, in _make_token_request
    raise GoogleAuthError('Token request failed: {}'.format(e))
hangups.auth.GoogleAuthError: Token request failed: 400 Client Error: Bad Request for url: https://accounts.google.com/o/oauth2/token
16:33:46 ERROR root: Valid login required, exiting
```

**Comment by Terrance** [comment]
> `hangups.auth.GoogleAuthError: Refresh token not found`

cookies.json is missing or not a valid token, so it's starting a fresh authentication, which suggests you haven't [copied the token file from hangups to hangoutsbot](https://github.com/hangoutsbot/hangoutsbot/issues/966#issuecomment-666750860) after doing your manual login.

**Comment by ghost** [comment]
> The token from hangups can be found at `~/.cache/hangups/refresh_token.txt`, copy it to `~/.local/share/hangoutsbot/cookies.json` for hangoutsbot to use it.

What's the path for that on Windows?

**Comment by Terrance** [comment]
Most likely both in `~/AppData/Roaming`, but you can check from a Python shell:

```python
>>> import appdirs
>>> appdirs.AppDirs('hangups', 'hangups').user_cache_dir
'/home/user/.cache/hangups'
>>> appdirs.AppDirs('hangupsbot', 'hangupsbot').user_data_dir
'/home/user/.local/share/hangupsbot'
```

**Comment by ghost** [comment]
Alright ty

**Comment by ghost** [comment]
What do I put in the `config.json`?

**Comment by Terrance** [comment]
For the token, nothing -- you should've copied it to default location (see `--help`).

For anything else, that's not relevant to this issue -- [read the wiki](https://github.com/hangoutsbot/hangoutsbot/wiki/Configuration) and raise a new one if needed.  (If you don't have an initial config file, a default one will be created.)

**Comment by ghost** [comment]
The default location doesn't exist on my device. I can't find it.

**Comment by ghost** [comment]
Hey guys. I'm so stupid. I just did the installation instructions all over again and it works. IDK what was wrong. Sorry for wasting your time.

**Comment by ghost** [comment]
Now I'm getting this error. Sorry if the answer is obvious:
```
08:46:54 ERROR asyncio: Exception in callback HangupsBot._on_event.<locals>.<lambda>(<Task finishe...ot iterable")>) at C:\Users\bekfe\OneDrive\Desktop\google-chat-bot\hangoutsbot\hangupsbot\hangupsbot.py:633
handle: <Handle HangupsBot._on_event.<locals>.<lambda>(<Task finishe...ot iterable")>) at C:\Users\bekfe\OneDrive\Desktop\google-chat-bot\hangoutsbot\hangupsbot\hangupsbot.py:633>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\bekfe\OneDrive\Desktop\google-chat-bot\hangoutsbot\hangupsbot\hangupsbot.py", line 633, in <lambda>
    ).add_done_callback(lambda future: future.result())
  File "C:\Users\bekfe\OneDrive\Desktop\google-chat-bot\hangoutsbot\hangupsbot\handlers.py", line 293, in handle_chat_message
    yield from self.handle_command(event)
  File "C:\Users\bekfe\OneDrive\Desktop\google-chat-bot\hangoutsbot\hangupsbot\handlers.py", line 336, in handle_command
    yield from self.bot.coro_send_message(event.conv, _('{}: Missing parameter(s)').format(
  File "C:\Users\bekfe\OneDrive\Desktop\google-chat-bot\hangoutsbot\hangupsbot\hangupsbot.py", line 780, in coro_send_message
    yield from _fc.send_message( response[1],
  File "C:\Users\bekfe\OneDrive\Desktop\google-chat-bot\hangoutsbot\hangupsbot\hangups_conversation.py", line 242, in send_message
    with (yield from asyncio.Lock()):
TypeError: 'Lock' object is not iterable
```

**Comment by ghost** [comment]
I did some Googling, and got it working by downgrading my Python version from 3.9 to 3.7.
