### ISSUE TITLE
Network Error 401 Unauthorized

### ISSUE THREAD

**Issue by stephenuwu** [hangoutsbot/hangoutsbot#968]
## Description
Recently, when someone runs a bot command, the bot will not respond occasionally. This happens like 50% of the time and most of the time you pretty much just have to rerun the command a couple times for it to work. This wasn't happening before so I'm not sure if it has something to do with the commands I wrote or my internet problem etc.
## Output of `/bot version`
Bot Version: 3.0.1
Python Version: 3.8.3
* aiohttp 3.6.2
* appdirs 1.4.4
* emoji 0.5.4
* hangups 0.4.10
* telepot 12.7
## Log output
```
Traceback (most recent call last):
  File "hangupsbot.py", line 780, in coro_send_message
    yield from _fc.send_message( response[1],
  File "/~location~/hangups_conversation.py", line 243, in send_message
    yield from self._client.send_chat_message(
  File "/usr/local/lib/python3.8/site-packages/hangups/client.py", line 590, in send_chat_message
    await self._pb_request('conversations/sendchatmessage',
  File "/usr/local/lib/python3.8/site-packages/hangups/client.py", line 413, in _pb_request
    res = await self._base_request(
  File "/usr/local/lib/python3.8/site-packages/hangups/client.py", line 469, in _base_request
    res = await self._session.fetch(
  File "/usr/local/lib/python3.8/site-packages/hangups/http_utils.py", line 86, in fetch
    raise exceptions.NetworkError(
hangups.exceptions.NetworkError: Request return unexpected status: 401: Unauthorized
```

**Comment by Terrance** [comment]
Upstream issue: https://github.com/tdryer/hangups/issues/498

**Comment by stephenuwu** [comment]
Alright thanks, I'll check it out.

**Comment by Terrance** [comment]
Said issue has been fixed, with a new version of hangups released, so the staging branch of hangoutsbot will now require it.
