### ISSUE TITLE
Wiki command should trim content of long pages

### ISSUE THREAD

**Issue by ghost** [hangoutsbot/hangoutsbot#971]
## Description
The /wiki command responds nothing, then shows this error in console:
```
09:11:41 INFO event: len/tx: 22//bot wiki Donald Trump
09:11:43 ERROR root: CORO_SEND_MESSAGE: error sending UgwvPCnHxHfQ6tJ1bd54AaABAQ
Traceback (most recent call last):
  File "hangupsbot/hangupsbot.py", line 782, in coro_send_message
    context = context )
  File "C:\Users\bekfe\OneDrive\Desktop\google-chat-bot\hangoutsbot\hangupsbot\hangups_conversation.py", line 252, in send_message
    expected_otr = otr_status )))
  File "C:\Users\bekfe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\hangups\client.py", line 593, in send_chat_message
    send_chat_message_request, response)
  File "C:\Users\bekfe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\hangups\client.py", line 437, in _pb_request
    .format(status, description)
```
Furthermore, it stops all other commands from working until I press the ESC key in the command prompt a few times.
## Output of `/bot version`
```
Bot Version: 3.0.1
Git: 2021-01-26 aabe105
diff --git a/requirements.txt b/requirements.txt
index 0f88484..19db980 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,7 +1,6 @@
 # BOT DEPENDENCIES #
 
 appdirs
-asyncio
 aiohttp>=3.3,<4
 hangups>=0.4.11
 ReParser==1.4.3+
Python Version: 3.7.9
* aiohttp 3.7.4.post0
* appdirs 1.4.4
* emoji 1.6.0
* hangups 0.4.14
* telepot 12.7
```
## Expected behaviour
It will give a snippet of the Wikipedia page
## Actual behaviour
The /wiki command responds nothing, then shows this error in console:
```
09:11:41 INFO event: len/tx: 22//bot wiki Donald Trump
09:11:43 ERROR root: CORO_SEND_MESSAGE: error sending UgwvPCnHxHfQ6tJ1bd54AaABAQ
Traceback (most recent call last):
  File "hangupsbot/hangupsbot.py", line 782, in coro_send_message
    context = context )
  File "C:\Users\bekfe\OneDrive\Desktop\google-chat-bot\hangoutsbot\hangupsbot\hangups_conversation.py", line 252, in send_message
    expected_otr = otr_status )))
  File "C:\Users\bekfe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\hangups\client.py", line 593, in send_chat_message
    send_chat_message_request, response)
  File "C:\Users\bekfe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\hangups\client.py", line 437, in _pb_request
    .format(status, description)
```
Furthermore, it stops all other commands from working until I press the ESC key in the command prompt a few times.
## Steps to reproduce:
  1. Install wiki plugin
  2. Use /wiki command
  3. Boom
## Log output

```
09:11:41 INFO event: len/tx: 22//bot wiki Donald Trump
09:11:43 ERROR root: CORO_SEND_MESSAGE: error sending UgwvPCnHxHfQ6tJ1bd54AaABAQ
Traceback (most recent call last):
  File "hangupsbot/hangupsbot.py", line 782, in coro_send_message
    context = context )
  File "C:\Users\bekfe\OneDrive\Desktop\google-chat-bot\hangoutsbot\hangupsbot\hangups_conversation.py", line 252, in send_message
    expected_otr = otr_status )))
  File "C:\Users\bekfe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\hangups\client.py", line 593, in send_chat_message
    send_chat_message_request, response)
  File "C:\Users\bekfe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\hangups\client.py", line 437, in _pb_request
    .format(status, description)
```

**Comment by Terrance** [comment]
You've only included half the traceback, so I can't see what the actual exception is.  Please post the full error message (up to the next timestamped line).

**Comment by ghost** [comment]
> You've only included half the traceback, so I can't see what the actual exception is. Please post the full error message (up to the next timestamped line).

Alright. I'll get it in a second.

**Comment by ghost** [comment]
Here you go:

```
12:24:22 INFO event: len/tx: 22//bot wiki Donald Trump
12:24:24 ERROR root: CORO_SEND_MESSAGE: error sending UgwvPCnHxHfQ6tJ1bd54AaABAQ
Traceback (most recent call last):
  File "hangupsbot.py", line 782, in coro_send_message
    context = context )
  File "C:\Users\bekfe\OneDrive\Desktop\google-chat-bot\hangoutsbot\hangupsbot\hangups_conversation.py", line 252, in send_message
    expected_otr = otr_status )))
  File "C:\Users\bekfe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\hangups\client.py", line 593, in send_chat_message
    send_chat_message_request, response)
  File "C:\Users\bekfe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\hangups\client.py", line 437, in _pb_request
    .format(status, description)
hangups.exceptions.NetworkError: Request failed with status 4: 'MessageContent size is too big'
```
